// Code generated by Fern. DO NOT EDIT.

package projects

import (
	context "context"

	nordlet "github.com/nordlet/nordlet-sdk-go"
	core "github.com/nordlet/nordlet-sdk-go/core"
	internal "github.com/nordlet/nordlet-sdk-go/internal"
	option "github.com/nordlet/nordlet-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (c *Client) PostV1ProjectsCreate(
	ctx context.Context,
	request *nordlet.PostV1ProjectsCreateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ProjectsCreateResponse, error) {
	response, err := c.WithRawResponse.PostV1ProjectsCreate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ProjectsUpdate(
	ctx context.Context,
	request *nordlet.PostV1ProjectsUpdateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ProjectsUpdateResponse, error) {
	response, err := c.WithRawResponse.PostV1ProjectsUpdate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ProjectsGet(
	ctx context.Context,
	request *nordlet.PostV1ProjectsGetRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ProjectsGetResponse, error) {
	response, err := c.WithRawResponse.PostV1ProjectsGet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ProjectsList(
	ctx context.Context,
	request *nordlet.PostV1ProjectsListRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ProjectsListResponse, error) {
	response, err := c.WithRawResponse.PostV1ProjectsList(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ProjectsTimeEntriesCreate(
	ctx context.Context,
	request *nordlet.PostV1ProjectsTimeEntriesCreateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ProjectsTimeEntriesCreateResponse, error) {
	response, err := c.WithRawResponse.PostV1ProjectsTimeEntriesCreate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ProjectsTimeEntriesUpdate(
	ctx context.Context,
	request *nordlet.PostV1ProjectsTimeEntriesUpdateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ProjectsTimeEntriesUpdateResponse, error) {
	response, err := c.WithRawResponse.PostV1ProjectsTimeEntriesUpdate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ProjectsTimeEntriesDelete(
	ctx context.Context,
	request *nordlet.PostV1ProjectsTimeEntriesDeleteRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ProjectsTimeEntriesDeleteResponse, error) {
	response, err := c.WithRawResponse.PostV1ProjectsTimeEntriesDelete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ProjectsTimeEntriesList(
	ctx context.Context,
	request *nordlet.PostV1ProjectsTimeEntriesListRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ProjectsTimeEntriesListResponse, error) {
	response, err := c.WithRawResponse.PostV1ProjectsTimeEntriesList(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ProjectsTimeEntriesBill(
	ctx context.Context,
	request *nordlet.PostV1ProjectsTimeEntriesBillRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ProjectsTimeEntriesBillResponse, error) {
	response, err := c.WithRawResponse.PostV1ProjectsTimeEntriesBill(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ProjectsReport(
	ctx context.Context,
	request *nordlet.PostV1ProjectsReportRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ProjectsReportResponse, error) {
	response, err := c.WithRawResponse.PostV1ProjectsReport(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
