// Code generated by Fern. DO NOT EDIT.

package projects

import (
	context "context"
	http "net/http"

	nordlet "github.com/nordlet/nordlet-sdk-go"
	core "github.com/nordlet/nordlet-sdk-go/core"
	internal "github.com/nordlet/nordlet-sdk-go/internal"
	option "github.com/nordlet/nordlet-sdk-go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) PostV1ProjectsCreate(
	ctx context.Context,
	request *nordlet.PostV1ProjectsCreateRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1ProjectsCreateResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/projects/create"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1ProjectsCreateResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1ProjectsCreateResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1ProjectsUpdate(
	ctx context.Context,
	request *nordlet.PostV1ProjectsUpdateRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1ProjectsUpdateResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/projects/update"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1ProjectsUpdateResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1ProjectsUpdateResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1ProjectsGet(
	ctx context.Context,
	request *nordlet.PostV1ProjectsGetRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1ProjectsGetResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/projects/get"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1ProjectsGetResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1ProjectsGetResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1ProjectsList(
	ctx context.Context,
	request *nordlet.PostV1ProjectsListRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1ProjectsListResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/projects/list"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1ProjectsListResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1ProjectsListResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1ProjectsTimeEntriesCreate(
	ctx context.Context,
	request *nordlet.PostV1ProjectsTimeEntriesCreateRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1ProjectsTimeEntriesCreateResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/projects/time-entries/create"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1ProjectsTimeEntriesCreateResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1ProjectsTimeEntriesCreateResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1ProjectsTimeEntriesUpdate(
	ctx context.Context,
	request *nordlet.PostV1ProjectsTimeEntriesUpdateRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1ProjectsTimeEntriesUpdateResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/projects/time-entries/update"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1ProjectsTimeEntriesUpdateResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1ProjectsTimeEntriesUpdateResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1ProjectsTimeEntriesDelete(
	ctx context.Context,
	request *nordlet.PostV1ProjectsTimeEntriesDeleteRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1ProjectsTimeEntriesDeleteResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/projects/time-entries/delete"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1ProjectsTimeEntriesDeleteResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1ProjectsTimeEntriesDeleteResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1ProjectsTimeEntriesList(
	ctx context.Context,
	request *nordlet.PostV1ProjectsTimeEntriesListRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1ProjectsTimeEntriesListResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/projects/time-entries/list"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1ProjectsTimeEntriesListResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1ProjectsTimeEntriesListResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1ProjectsTimeEntriesBill(
	ctx context.Context,
	request *nordlet.PostV1ProjectsTimeEntriesBillRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1ProjectsTimeEntriesBillResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/projects/time-entries/bill"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1ProjectsTimeEntriesBillResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1ProjectsTimeEntriesBillResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1ProjectsReport(
	ctx context.Context,
	request *nordlet.PostV1ProjectsReportRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1ProjectsReportResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/projects/report"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1ProjectsReportResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1ProjectsReportResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
