// Code generated by Fern. DO NOT EDIT.

package bank_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	nordlet "github.com/nordlet/nordlet-sdk-go"
	client "github.com/nordlet/nordlet-sdk-go/client"
	option "github.com/nordlet/nordlet-sdk-go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestBankPostV1BankAccountsCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankAccountsCreateRequest{
		Name: "name",
	}
	_, invocationErr := client.Bank.PostV1BankAccountsCreate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankAccountsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankAccountsCreateWithWireMock", "POST", "/v1/bank/accounts/create", nil, 1)
}

func TestBankPostV1BankAccountsListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankAccountsListRequest{}
	_, invocationErr := client.Bank.PostV1BankAccountsList(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankAccountsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankAccountsListWithWireMock", "POST", "/v1/bank/accounts/list", nil, 1)
}

func TestBankPostV1BankAccountsUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankAccountsUpdateRequest{
		ID: "id",
	}
	_, invocationErr := client.Bank.PostV1BankAccountsUpdate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankAccountsUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankAccountsUpdateWithWireMock", "POST", "/v1/bank/accounts/update", nil, 1)
}

func TestBankPostV1BankTransactionsImportWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankTransactionsImportRequest{
		BankAccountID: "bankAccountId",
		Transactions: []*nordlet.PostV1BankTransactionsImportRequestTransactionsItem{
			&nordlet.PostV1BankTransactionsImportRequestTransactionsItem{
				Date:   "date",
				Amount: "amount",
			},
		},
	}
	_, invocationErr := client.Bank.PostV1BankTransactionsImport(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankTransactionsImportWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankTransactionsImportWithWireMock", "POST", "/v1/bank/transactions/import", nil, 1)
}

func TestBankPostV1BankStatementsImportWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankStatementsImportRequest{
		BankAccountID: "bankAccountId",
		Content:       "content",
	}
	_, invocationErr := client.Bank.PostV1BankStatementsImport(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankStatementsImportWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankStatementsImportWithWireMock", "POST", "/v1/bank/statements/import", nil, 1)
}

func TestBankPostV1BankTransactionsListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankTransactionsListRequest{}
	_, invocationErr := client.Bank.PostV1BankTransactionsList(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankTransactionsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankTransactionsListWithWireMock", "POST", "/v1/bank/transactions/list", nil, 1)
}

func TestBankPostV1BankTransactionsMatchWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankTransactionsMatchRequest{
		TransactionID: "transactionId",
		DocumentType:  nordlet.PostV1BankTransactionsMatchRequestDocumentTypeSaleInvoice,
		DocumentID:    "documentId",
	}
	_, invocationErr := client.Bank.PostV1BankTransactionsMatch(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankTransactionsMatchWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankTransactionsMatchWithWireMock", "POST", "/v1/bank/transactions/match", nil, 1)
}

func TestBankPostV1BankTransactionsRecordWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankTransactionsRecordRequest{
		BankAccountID: "bankAccountId",
		Date:          "date",
		Amount:        "amount",
		DocumentType:  nordlet.PostV1BankTransactionsRecordRequestDocumentTypeSaleInvoice,
		DocumentID:    "documentId",
	}
	_, invocationErr := client.Bank.PostV1BankTransactionsRecord(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankTransactionsRecordWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankTransactionsRecordWithWireMock", "POST", "/v1/bank/transactions/record", nil, 1)
}

func TestBankPostV1BankPaymentsExportWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankPaymentsExportRequest{
		BankAccountID: "bankAccountId",
		PurchaseInvoiceIDs: []string{
			"purchaseInvoiceIds",
		},
	}
	_, invocationErr := client.Bank.PostV1BankPaymentsExport(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankPaymentsExportWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankPaymentsExportWithWireMock", "POST", "/v1/bank/payments/export", nil, 1)
}

func TestBankCreateABankImportTemplateFieldsDefaultToTheTypesStandardFieldListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankImportTemplatesCreateRequest{
		Name: "name",
		Type: nordlet.PostV1BankImportTemplatesCreateRequestTypeStripe,
	}
	_, invocationErr := client.Bank.CreateABankImportTemplateFieldsDefaultToTheTypesStandardFieldList(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankCreateABankImportTemplateFieldsDefaultToTheTypesStandardFieldListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankCreateABankImportTemplateFieldsDefaultToTheTypesStandardFieldListWithWireMock", "POST", "/v1/bank/import-templates/create", nil, 1)
}

func TestBankPostV1BankImportTemplatesUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankImportTemplatesUpdateRequest{
		ID: "id",
	}
	_, invocationErr := client.Bank.PostV1BankImportTemplatesUpdate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankImportTemplatesUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankImportTemplatesUpdateWithWireMock", "POST", "/v1/bank/import-templates/update", nil, 1)
}

func TestBankPostV1BankImportTemplatesDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankImportTemplatesDeleteRequest{
		ID: "id",
	}
	_, invocationErr := client.Bank.PostV1BankImportTemplatesDelete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankImportTemplatesDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankImportTemplatesDeleteWithWireMock", "POST", "/v1/bank/import-templates/delete", nil, 1)
}

func TestBankPostV1BankImportTemplatesGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankImportTemplatesGetRequest{
		ID: "id",
	}
	_, invocationErr := client.Bank.PostV1BankImportTemplatesGet(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankImportTemplatesGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankImportTemplatesGetWithWireMock", "POST", "/v1/bank/import-templates/get", nil, 1)
}

func TestBankPostV1BankImportTemplatesListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankImportTemplatesListRequest{}
	_, invocationErr := client.Bank.PostV1BankImportTemplatesList(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankImportTemplatesListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankImportTemplatesListWithWireMock", "POST", "/v1/bank/import-templates/list", nil, 1)
}

func TestBankPostV1BankMatchRulesCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankMatchRulesCreateRequest{
		Name:    "name",
		Pattern: "pattern",
	}
	_, invocationErr := client.Bank.PostV1BankMatchRulesCreate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankMatchRulesCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankMatchRulesCreateWithWireMock", "POST", "/v1/bank/match-rules/create", nil, 1)
}

func TestBankPostV1BankMatchRulesUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankMatchRulesUpdateRequest{
		ID: "id",
	}
	_, invocationErr := client.Bank.PostV1BankMatchRulesUpdate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankMatchRulesUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankMatchRulesUpdateWithWireMock", "POST", "/v1/bank/match-rules/update", nil, 1)
}

func TestBankPostV1BankMatchRulesDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankMatchRulesDeleteRequest{
		ID: "id",
	}
	_, invocationErr := client.Bank.PostV1BankMatchRulesDelete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankMatchRulesDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankMatchRulesDeleteWithWireMock", "POST", "/v1/bank/match-rules/delete", nil, 1)
}

func TestBankPostV1BankMatchRulesListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankMatchRulesListRequest{}
	_, invocationErr := client.Bank.PostV1BankMatchRulesList(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankMatchRulesListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankMatchRulesListWithWireMock", "POST", "/v1/bank/match-rules/list", nil, 1)
}

func TestBankPostV1BankMandatesCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankMandatesCreateRequest{
		PartnerID:     "partnerId",
		Iban:          "iban",
		SignatureDate: "signatureDate",
	}
	_, invocationErr := client.Bank.PostV1BankMandatesCreate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankMandatesCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankMandatesCreateWithWireMock", "POST", "/v1/bank/mandates/create", nil, 1)
}

func TestBankPostV1BankMandatesUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankMandatesUpdateRequest{
		ID: "id",
	}
	_, invocationErr := client.Bank.PostV1BankMandatesUpdate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankMandatesUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankMandatesUpdateWithWireMock", "POST", "/v1/bank/mandates/update", nil, 1)
}

func TestBankPostV1BankMandatesCancelWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankMandatesCancelRequest{
		ID: "id",
	}
	_, invocationErr := client.Bank.PostV1BankMandatesCancel(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankMandatesCancelWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankMandatesCancelWithWireMock", "POST", "/v1/bank/mandates/cancel", nil, 1)
}

func TestBankPostV1BankMandatesGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankMandatesGetRequest{
		ID: "id",
	}
	_, invocationErr := client.Bank.PostV1BankMandatesGet(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankMandatesGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankMandatesGetWithWireMock", "POST", "/v1/bank/mandates/get", nil, 1)
}

func TestBankPostV1BankMandatesListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankMandatesListRequest{}
	_, invocationErr := client.Bank.PostV1BankMandatesList(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankMandatesListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankMandatesListWithWireMock", "POST", "/v1/bank/mandates/list", nil, 1)
}

func TestBankPostV1BankDirectDebitsExportWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankDirectDebitsExportRequest{
		BankAccountID: "bankAccountId",
		SaleInvoiceIDs: []string{
			"saleInvoiceIds",
		},
	}
	_, invocationErr := client.Bank.PostV1BankDirectDebitsExport(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankDirectDebitsExportWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankDirectDebitsExportWithWireMock", "POST", "/v1/bank/direct-debits/export", nil, 1)
}

func TestBankPostV1BankTransactionsSuggestMatchesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankTransactionsSuggestMatchesRequest{
		TransactionID: "transactionId",
	}
	_, invocationErr := client.Bank.PostV1BankTransactionsSuggestMatches(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankTransactionsSuggestMatchesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankTransactionsSuggestMatchesWithWireMock", "POST", "/v1/bank/transactions/suggest-matches", nil, 1)
}

func TestBankPostV1BankSettlementsImportWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankSettlementsImportRequest{
		BankAccountID: "bankAccountId",
		Content:       "content",
	}
	_, invocationErr := client.Bank.PostV1BankSettlementsImport(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankSettlementsImportWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankSettlementsImportWithWireMock", "POST", "/v1/bank/settlements/import", nil, 1)
}

func TestBankPostV1BankSettlementsListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankSettlementsListRequest{}
	_, invocationErr := client.Bank.PostV1BankSettlementsList(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankSettlementsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankSettlementsListWithWireMock", "POST", "/v1/bank/settlements/list", nil, 1)
}

func TestBankPostV1BankSettlementsGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankSettlementsGetRequest{
		ID: "id",
	}
	_, invocationErr := client.Bank.PostV1BankSettlementsGet(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankSettlementsGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankSettlementsGetWithWireMock", "POST", "/v1/bank/settlements/get", nil, 1)
}

func TestBankPostV1BankSettlementsMatchWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankSettlementsMatchRequest{
		LineID: "lineId",
	}
	_, invocationErr := client.Bank.PostV1BankSettlementsMatch(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankSettlementsMatchWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankSettlementsMatchWithWireMock", "POST", "/v1/bank/settlements/match", nil, 1)
}

func TestBankPostV1BankSettlementsLinkWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankSettlementsLinkRequest{
		ID:                "id",
		BankTransactionID: "bankTransactionId",
	}
	_, invocationErr := client.Bank.PostV1BankSettlementsLink(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankSettlementsLinkWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankSettlementsLinkWithWireMock", "POST", "/v1/bank/settlements/link", nil, 1)
}

func TestBankPostV1BankSettlementsUnlinkWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankSettlementsUnlinkRequest{
		ID: "id",
	}
	_, invocationErr := client.Bank.PostV1BankSettlementsUnlink(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankSettlementsUnlinkWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankSettlementsUnlinkWithWireMock", "POST", "/v1/bank/settlements/unlink", nil, 1)
}

func TestBankPostV1BankSettlementsPostWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankSettlementsPostRequest{
		ID: "id",
	}
	_, invocationErr := client.Bank.PostV1BankSettlementsPost(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankSettlementsPostWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankSettlementsPostWithWireMock", "POST", "/v1/bank/settlements/post", nil, 1)
}

func TestBankListThePsd2BanksAspsPsAvailableToConnectWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankFeedsBanksListRequest{}
	_, invocationErr := client.Bank.ListThePsd2BanksAspsPsAvailableToConnect(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankListThePsd2BanksAspsPsAvailableToConnectWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankListThePsd2BanksAspsPsAvailableToConnectWithWireMock", "POST", "/v1/bank/feeds/banks/list", nil, 1)
}

func TestBankBeginBankAuthorizationRedirectTheUserToTheReturnedURLWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankFeedsConnectionsStartRequest{
		AspspName:    "aspspName",
		AspspCountry: "aspspCountry",
	}
	_, invocationErr := client.Bank.BeginBankAuthorizationRedirectTheUserToTheReturnedURL(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankBeginBankAuthorizationRedirectTheUserToTheReturnedURLWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankBeginBankAuthorizationRedirectTheUserToTheReturnedURLWithWireMock", "POST", "/v1/bank/feeds/connections/start", nil, 1)
}

func TestBankExchangeTheRedirectCodeForASessionAndStoreTheBankAccountsItExposesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankFeedsConnectionsCompleteRequest{
		Reference: "reference",
		Code:      "code",
	}
	_, invocationErr := client.Bank.ExchangeTheRedirectCodeForASessionAndStoreTheBankAccountsItExposes(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankExchangeTheRedirectCodeForASessionAndStoreTheBankAccountsItExposesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankExchangeTheRedirectCodeForASessionAndStoreTheBankAccountsItExposesWithWireMock", "POST", "/v1/bank/feeds/connections/complete", nil, 1)
}

func TestBankPostV1BankFeedsConnectionsGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankFeedsConnectionsGetRequest{
		ID: "id",
	}
	_, invocationErr := client.Bank.PostV1BankFeedsConnectionsGet(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankFeedsConnectionsGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankFeedsConnectionsGetWithWireMock", "POST", "/v1/bank/feeds/connections/get", nil, 1)
}

func TestBankPostV1BankFeedsConnectionsListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankFeedsConnectionsListRequest{}
	_, invocationErr := client.Bank.PostV1BankFeedsConnectionsList(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPostV1BankFeedsConnectionsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPostV1BankFeedsConnectionsListWithWireMock", "POST", "/v1/bank/feeds/connections/list", nil, 1)
}

func TestBankRevokeTheConsentAtTheBankAndDropTheStoredConnectionWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankFeedsConnectionsDeleteRequest{
		ID: "id",
	}
	_, invocationErr := client.Bank.RevokeTheConsentAtTheBankAndDropTheStoredConnection(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankRevokeTheConsentAtTheBankAndDropTheStoredConnectionWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankRevokeTheConsentAtTheBankAndDropTheStoredConnectionWithWireMock", "POST", "/v1/bank/feeds/connections/delete", nil, 1)
}

func TestBankPointABankFeedAccountAtALedgerBankAccountSoItsTransactionsCanBeSyncedWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankFeedsAccountsLinkRequest{
		ID: "id",
	}
	_, invocationErr := client.Bank.PointABankFeedAccountAtALedgerBankAccountSoItsTransactionsCanBeSynced(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPointABankFeedAccountAtALedgerBankAccountSoItsTransactionsCanBeSyncedWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPointABankFeedAccountAtALedgerBankAccountSoItsTransactionsCanBeSyncedWithWireMock", "POST", "/v1/bank/feeds/accounts/link", nil, 1)
}

func TestBankChooseTheImportTemplateAppliedOnSyncAndHowOftenTheAccountIsSyncedAutomaticallyWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankFeedsAccountsConfigureRequest{
		ID: "id",
	}
	_, invocationErr := client.Bank.ChooseTheImportTemplateAppliedOnSyncAndHowOftenTheAccountIsSyncedAutomatically(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankChooseTheImportTemplateAppliedOnSyncAndHowOftenTheAccountIsSyncedAutomaticallyWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankChooseTheImportTemplateAppliedOnSyncAndHowOftenTheAccountIsSyncedAutomaticallyWithWireMock", "POST", "/v1/bank/feeds/accounts/configure", nil, 1)
}

func TestBankPullNewTransactionsFromTheBankIntoTheLedgerEmitsBankFeedSyncedWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostV1BankFeedsSyncRequest{
		ConnectionID: "connectionId",
	}
	_, invocationErr := client.Bank.PullNewTransactionsFromTheBankIntoTheLedgerEmitsBankFeedSynced(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBankPullNewTransactionsFromTheBankIntoTheLedgerEmitsBankFeedSyncedWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBankPullNewTransactionsFromTheBankIntoTheLedgerEmitsBankFeedSyncedWithWireMock", "POST", "/v1/bank/feeds/sync", nil, 1)
}
