// Code generated by Fern. DO NOT EDIT.

package migration

import (
	context "context"

	nordlet "github.com/nordlet/nordlet-sdk-go"
	core "github.com/nordlet/nordlet-sdk-go/core"
	internal "github.com/nordlet/nordlet-sdk-go/internal"
	option "github.com/nordlet/nordlet-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Runs every check the import runs (accounts, partners, balances, open invoices, assets, stock) and returns the same summary and warnings, then rolls everything back. Nothing is stored.
func (c *Client) CheckAHistoricalBooksPackageWithoutWritingAnything(
	ctx context.Context,
	request *nordlet.PostV1MigrationBooksValidateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1MigrationBooksValidateResponse, error) {
	response, err := c.WithRawResponse.CheckAHistoricalBooksPackageWithoutWritingAnything(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Brings a company over from another system in one call: chart of accounts, partners, items, opening balances (or the full journal history), open customer and supplier invoices, fixed assets with their accumulated depreciation, and stock on hand. The whole package is written in one database transaction — if any row fails, nothing is stored.
func (c *Client) ImportHistoricalBooksFromAPreviousAccountingSystem(
	ctx context.Context,
	request *nordlet.PostV1MigrationBooksImportRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1MigrationBooksImportResponse, error) {
	response, err := c.WithRawResponse.ImportHistoricalBooksFromAPreviousAccountingSystem(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
