// Code generated by Fern. DO NOT EDIT.

package peppol

import (
	context "context"
	http "net/http"

	nordlet "github.com/nordlet/nordlet-sdk-go"
	core "github.com/nordlet/nordlet-sdk-go/core"
	internal "github.com/nordlet/nordlet-sdk-go/internal"
	option "github.com/nordlet/nordlet-sdk-go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) ParticipantsLookup(
	ctx context.Context,
	request *nordlet.ParticipantsLookupPeppolRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.ParticipantsLookupPeppolResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/peppol/participants/lookup"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.ParticipantsLookupPeppolResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.ParticipantsLookupPeppolResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Webhooks(
	ctx context.Context,
	request *nordlet.WebhooksPeppolRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.WebhooksPeppolResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/peppol/webhooks/%v/%v",
		request.Provider,
		request.CompanyID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *nordlet.WebhooksPeppolResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.WebhooksPeppolResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
