// Code generated by Fern. DO NOT EDIT.

package nordlet

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/nordlet/nordlet-sdk-go/internal"
	big "math/big"
	time "time"
)

var (
	createDocumentSeriesRequestFieldDocumentType    = big.NewInt(1 << 0)
	createDocumentSeriesRequestFieldPrefix          = big.NewInt(1 << 1)
	createDocumentSeriesRequestFieldName            = big.NewInt(1 << 2)
	createDocumentSeriesRequestFieldLabel           = big.NewInt(1 << 3)
	createDocumentSeriesRequestFieldOperationTypeID = big.NewInt(1 << 4)
	createDocumentSeriesRequestFieldNumberLength    = big.NewInt(1 << 5)
	createDocumentSeriesRequestFieldNextNumber      = big.NewInt(1 << 6)
	createDocumentSeriesRequestFieldAllocatedFrom   = big.NewInt(1 << 7)
	createDocumentSeriesRequestFieldAllocatedTo     = big.NewInt(1 << 8)
	createDocumentSeriesRequestFieldWarehouseID     = big.NewInt(1 << 9)
	createDocumentSeriesRequestFieldPrintSeries     = big.NewInt(1 << 10)
	createDocumentSeriesRequestFieldIsDefault       = big.NewInt(1 << 11)
	createDocumentSeriesRequestFieldIsActive        = big.NewInt(1 << 12)
)

type CreateDocumentSeriesRequest struct {
	DocumentType    *CreateDocumentSeriesRequestDocumentType `json:"documentType,omitempty" url:"-"`
	Prefix          string                                   `json:"prefix" url:"-"`
	Name            *string                                  `json:"name,omitempty" url:"-"`
	Label           *string                                  `json:"label,omitempty" url:"-"`
	OperationTypeID *string                                  `json:"operationTypeId,omitempty" url:"-"`
	NumberLength    *int64                                   `json:"numberLength,omitempty" url:"-"`
	NextNumber      *int64                                   `json:"nextNumber,omitempty" url:"-"`
	AllocatedFrom   *int64                                   `json:"allocatedFrom,omitempty" url:"-"`
	AllocatedTo     *int64                                   `json:"allocatedTo,omitempty" url:"-"`
	WarehouseID     *string                                  `json:"warehouseId,omitempty" url:"-"`
	PrintSeries     *bool                                    `json:"printSeries,omitempty" url:"-"`
	IsDefault       *bool                                    `json:"isDefault,omitempty" url:"-"`
	IsActive        *bool                                    `json:"isActive,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateDocumentSeriesRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetDocumentType sets the DocumentType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesRequest) SetDocumentType(documentType *CreateDocumentSeriesRequestDocumentType) {
	c.DocumentType = documentType
	c.require(createDocumentSeriesRequestFieldDocumentType)
}

// SetPrefix sets the Prefix field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesRequest) SetPrefix(prefix string) {
	c.Prefix = prefix
	c.require(createDocumentSeriesRequestFieldPrefix)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesRequest) SetName(name *string) {
	c.Name = name
	c.require(createDocumentSeriesRequestFieldName)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesRequest) SetLabel(label *string) {
	c.Label = label
	c.require(createDocumentSeriesRequestFieldLabel)
}

// SetOperationTypeID sets the OperationTypeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesRequest) SetOperationTypeID(operationTypeID *string) {
	c.OperationTypeID = operationTypeID
	c.require(createDocumentSeriesRequestFieldOperationTypeID)
}

// SetNumberLength sets the NumberLength field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesRequest) SetNumberLength(numberLength *int64) {
	c.NumberLength = numberLength
	c.require(createDocumentSeriesRequestFieldNumberLength)
}

// SetNextNumber sets the NextNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesRequest) SetNextNumber(nextNumber *int64) {
	c.NextNumber = nextNumber
	c.require(createDocumentSeriesRequestFieldNextNumber)
}

// SetAllocatedFrom sets the AllocatedFrom field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesRequest) SetAllocatedFrom(allocatedFrom *int64) {
	c.AllocatedFrom = allocatedFrom
	c.require(createDocumentSeriesRequestFieldAllocatedFrom)
}

// SetAllocatedTo sets the AllocatedTo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesRequest) SetAllocatedTo(allocatedTo *int64) {
	c.AllocatedTo = allocatedTo
	c.require(createDocumentSeriesRequestFieldAllocatedTo)
}

// SetWarehouseID sets the WarehouseID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesRequest) SetWarehouseID(warehouseID *string) {
	c.WarehouseID = warehouseID
	c.require(createDocumentSeriesRequestFieldWarehouseID)
}

// SetPrintSeries sets the PrintSeries field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesRequest) SetPrintSeries(printSeries *bool) {
	c.PrintSeries = printSeries
	c.require(createDocumentSeriesRequestFieldPrintSeries)
}

// SetIsDefault sets the IsDefault field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesRequest) SetIsDefault(isDefault *bool) {
	c.IsDefault = isDefault
	c.require(createDocumentSeriesRequestFieldIsDefault)
}

// SetIsActive sets the IsActive field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesRequest) SetIsActive(isActive *bool) {
	c.IsActive = isActive
	c.require(createDocumentSeriesRequestFieldIsActive)
}

func (c *CreateDocumentSeriesRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateDocumentSeriesRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateDocumentSeriesRequest(body)
	return nil
}

func (c *CreateDocumentSeriesRequest) MarshalJSON() ([]byte, error) {
	type embed CreateDocumentSeriesRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deleteDocumentSeriesRequestFieldID = big.NewInt(1 << 0)
)

type DeleteDocumentSeriesRequest struct {
	ID string `json:"id" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteDocumentSeriesRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteDocumentSeriesRequest) SetID(id string) {
	d.ID = id
	d.require(deleteDocumentSeriesRequestFieldID)
}

func (d *DeleteDocumentSeriesRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteDocumentSeriesRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*d = DeleteDocumentSeriesRequest(body)
	return nil
}

func (d *DeleteDocumentSeriesRequest) MarshalJSON() ([]byte, error) {
	type embed DeleteDocumentSeriesRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getDocumentSeriesRequestFieldID = big.NewInt(1 << 0)
)

type GetDocumentSeriesRequest struct {
	ID string `json:"id" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetDocumentSeriesRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDocumentSeriesRequest) SetID(id string) {
	g.ID = id
	g.require(getDocumentSeriesRequestFieldID)
}

func (g *GetDocumentSeriesRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GetDocumentSeriesRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GetDocumentSeriesRequest(body)
	return nil
}

func (g *GetDocumentSeriesRequest) MarshalJSON() ([]byte, error) {
	type embed GetDocumentSeriesRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	listDocumentSeriesRequestFieldPage     = big.NewInt(1 << 0)
	listDocumentSeriesRequestFieldPageSize = big.NewInt(1 << 1)
	listDocumentSeriesRequestFieldSort     = big.NewInt(1 << 2)
	listDocumentSeriesRequestFieldFilter   = big.NewInt(1 << 3)
	listDocumentSeriesRequestFieldTotals   = big.NewInt(1 << 4)
)

type ListDocumentSeriesRequest struct {
	Page     *int64                                 `json:"page,omitempty" url:"-"`
	PageSize *int64                                 `json:"pageSize,omitempty" url:"-"`
	Sort     []*ListDocumentSeriesRequestSortItem   `json:"sort,omitempty" url:"-"`
	Filter   []*ListDocumentSeriesRequestFilterItem `json:"filter,omitempty" url:"-"`
	// Numeric fields to sum over every row matching the filter (not only the current page)
	Totals []string `json:"totals,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListDocumentSeriesRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesRequest) SetPage(page *int64) {
	l.Page = page
	l.require(listDocumentSeriesRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesRequest) SetPageSize(pageSize *int64) {
	l.PageSize = pageSize
	l.require(listDocumentSeriesRequestFieldPageSize)
}

// SetSort sets the Sort field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesRequest) SetSort(sort []*ListDocumentSeriesRequestSortItem) {
	l.Sort = sort
	l.require(listDocumentSeriesRequestFieldSort)
}

// SetFilter sets the Filter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesRequest) SetFilter(filter []*ListDocumentSeriesRequestFilterItem) {
	l.Filter = filter
	l.require(listDocumentSeriesRequestFieldFilter)
}

// SetTotals sets the Totals field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesRequest) SetTotals(totals []string) {
	l.Totals = totals
	l.require(listDocumentSeriesRequestFieldTotals)
}

func (l *ListDocumentSeriesRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler ListDocumentSeriesRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*l = ListDocumentSeriesRequest(body)
	return nil
}

func (l *ListDocumentSeriesRequest) MarshalJSON() ([]byte, error) {
	type embed ListDocumentSeriesRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

type CreateDocumentSeriesRequestDocumentType string

const (
	CreateDocumentSeriesRequestDocumentTypeSaleInvoice    CreateDocumentSeriesRequestDocumentType = "sale_invoice"
	CreateDocumentSeriesRequestDocumentTypeSaleCreditNote CreateDocumentSeriesRequestDocumentType = "sale_credit_note"
	CreateDocumentSeriesRequestDocumentTypeSaleProforma   CreateDocumentSeriesRequestDocumentType = "sale_proforma"
	CreateDocumentSeriesRequestDocumentTypeSaleAdvance    CreateDocumentSeriesRequestDocumentType = "sale_advance"
)

func NewCreateDocumentSeriesRequestDocumentTypeFromString(s string) (CreateDocumentSeriesRequestDocumentType, error) {
	switch s {
	case "sale_invoice":
		return CreateDocumentSeriesRequestDocumentTypeSaleInvoice, nil
	case "sale_credit_note":
		return CreateDocumentSeriesRequestDocumentTypeSaleCreditNote, nil
	case "sale_proforma":
		return CreateDocumentSeriesRequestDocumentTypeSaleProforma, nil
	case "sale_advance":
		return CreateDocumentSeriesRequestDocumentTypeSaleAdvance, nil
	}
	var t CreateDocumentSeriesRequestDocumentType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateDocumentSeriesRequestDocumentType) Ptr() *CreateDocumentSeriesRequestDocumentType {
	return &c
}

var (
	createDocumentSeriesResponseFieldID              = big.NewInt(1 << 0)
	createDocumentSeriesResponseFieldDocumentType    = big.NewInt(1 << 1)
	createDocumentSeriesResponseFieldPrefix          = big.NewInt(1 << 2)
	createDocumentSeriesResponseFieldName            = big.NewInt(1 << 3)
	createDocumentSeriesResponseFieldLabel           = big.NewInt(1 << 4)
	createDocumentSeriesResponseFieldOperationTypeID = big.NewInt(1 << 5)
	createDocumentSeriesResponseFieldNumberLength    = big.NewInt(1 << 6)
	createDocumentSeriesResponseFieldNextNumber      = big.NewInt(1 << 7)
	createDocumentSeriesResponseFieldAllocatedFrom   = big.NewInt(1 << 8)
	createDocumentSeriesResponseFieldAllocatedTo     = big.NewInt(1 << 9)
	createDocumentSeriesResponseFieldWarehouseID     = big.NewInt(1 << 10)
	createDocumentSeriesResponseFieldPrintSeries     = big.NewInt(1 << 11)
	createDocumentSeriesResponseFieldIsDefault       = big.NewInt(1 << 12)
	createDocumentSeriesResponseFieldIsActive        = big.NewInt(1 << 13)
	createDocumentSeriesResponseFieldCreatedAt       = big.NewInt(1 << 14)
	createDocumentSeriesResponseFieldUpdatedAt       = big.NewInt(1 << 15)
)

type CreateDocumentSeriesResponse struct {
	ID              string    `json:"id" url:"id"`
	DocumentType    string    `json:"documentType" url:"documentType"`
	Prefix          string    `json:"prefix" url:"prefix"`
	Name            *string   `json:"name,omitempty" url:"name,omitempty"`
	Label           *string   `json:"label,omitempty" url:"label,omitempty"`
	OperationTypeID *string   `json:"operationTypeId,omitempty" url:"operationTypeId,omitempty"`
	NumberLength    int64     `json:"numberLength" url:"numberLength"`
	NextNumber      int64     `json:"nextNumber" url:"nextNumber"`
	AllocatedFrom   *int64    `json:"allocatedFrom,omitempty" url:"allocatedFrom,omitempty"`
	AllocatedTo     *int64    `json:"allocatedTo,omitempty" url:"allocatedTo,omitempty"`
	WarehouseID     *string   `json:"warehouseId,omitempty" url:"warehouseId,omitempty"`
	PrintSeries     bool      `json:"printSeries" url:"printSeries"`
	IsDefault       bool      `json:"isDefault" url:"isDefault"`
	IsActive        bool      `json:"isActive" url:"isActive"`
	CreatedAt       time.Time `json:"createdAt" url:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateDocumentSeriesResponse) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateDocumentSeriesResponse) GetDocumentType() string {
	if c == nil {
		return ""
	}
	return c.DocumentType
}

func (c *CreateDocumentSeriesResponse) GetPrefix() string {
	if c == nil {
		return ""
	}
	return c.Prefix
}

func (c *CreateDocumentSeriesResponse) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CreateDocumentSeriesResponse) GetLabel() *string {
	if c == nil {
		return nil
	}
	return c.Label
}

func (c *CreateDocumentSeriesResponse) GetOperationTypeID() *string {
	if c == nil {
		return nil
	}
	return c.OperationTypeID
}

func (c *CreateDocumentSeriesResponse) GetNumberLength() int64 {
	if c == nil {
		return 0
	}
	return c.NumberLength
}

func (c *CreateDocumentSeriesResponse) GetNextNumber() int64 {
	if c == nil {
		return 0
	}
	return c.NextNumber
}

func (c *CreateDocumentSeriesResponse) GetAllocatedFrom() *int64 {
	if c == nil {
		return nil
	}
	return c.AllocatedFrom
}

func (c *CreateDocumentSeriesResponse) GetAllocatedTo() *int64 {
	if c == nil {
		return nil
	}
	return c.AllocatedTo
}

func (c *CreateDocumentSeriesResponse) GetWarehouseID() *string {
	if c == nil {
		return nil
	}
	return c.WarehouseID
}

func (c *CreateDocumentSeriesResponse) GetPrintSeries() bool {
	if c == nil {
		return false
	}
	return c.PrintSeries
}

func (c *CreateDocumentSeriesResponse) GetIsDefault() bool {
	if c == nil {
		return false
	}
	return c.IsDefault
}

func (c *CreateDocumentSeriesResponse) GetIsActive() bool {
	if c == nil {
		return false
	}
	return c.IsActive
}

func (c *CreateDocumentSeriesResponse) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *CreateDocumentSeriesResponse) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}

func (c *CreateDocumentSeriesResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateDocumentSeriesResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesResponse) SetID(id string) {
	c.ID = id
	c.require(createDocumentSeriesResponseFieldID)
}

// SetDocumentType sets the DocumentType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesResponse) SetDocumentType(documentType string) {
	c.DocumentType = documentType
	c.require(createDocumentSeriesResponseFieldDocumentType)
}

// SetPrefix sets the Prefix field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesResponse) SetPrefix(prefix string) {
	c.Prefix = prefix
	c.require(createDocumentSeriesResponseFieldPrefix)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesResponse) SetName(name *string) {
	c.Name = name
	c.require(createDocumentSeriesResponseFieldName)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesResponse) SetLabel(label *string) {
	c.Label = label
	c.require(createDocumentSeriesResponseFieldLabel)
}

// SetOperationTypeID sets the OperationTypeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesResponse) SetOperationTypeID(operationTypeID *string) {
	c.OperationTypeID = operationTypeID
	c.require(createDocumentSeriesResponseFieldOperationTypeID)
}

// SetNumberLength sets the NumberLength field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesResponse) SetNumberLength(numberLength int64) {
	c.NumberLength = numberLength
	c.require(createDocumentSeriesResponseFieldNumberLength)
}

// SetNextNumber sets the NextNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesResponse) SetNextNumber(nextNumber int64) {
	c.NextNumber = nextNumber
	c.require(createDocumentSeriesResponseFieldNextNumber)
}

// SetAllocatedFrom sets the AllocatedFrom field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesResponse) SetAllocatedFrom(allocatedFrom *int64) {
	c.AllocatedFrom = allocatedFrom
	c.require(createDocumentSeriesResponseFieldAllocatedFrom)
}

// SetAllocatedTo sets the AllocatedTo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesResponse) SetAllocatedTo(allocatedTo *int64) {
	c.AllocatedTo = allocatedTo
	c.require(createDocumentSeriesResponseFieldAllocatedTo)
}

// SetWarehouseID sets the WarehouseID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesResponse) SetWarehouseID(warehouseID *string) {
	c.WarehouseID = warehouseID
	c.require(createDocumentSeriesResponseFieldWarehouseID)
}

// SetPrintSeries sets the PrintSeries field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesResponse) SetPrintSeries(printSeries bool) {
	c.PrintSeries = printSeries
	c.require(createDocumentSeriesResponseFieldPrintSeries)
}

// SetIsDefault sets the IsDefault field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesResponse) SetIsDefault(isDefault bool) {
	c.IsDefault = isDefault
	c.require(createDocumentSeriesResponseFieldIsDefault)
}

// SetIsActive sets the IsActive field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesResponse) SetIsActive(isActive bool) {
	c.IsActive = isActive
	c.require(createDocumentSeriesResponseFieldIsActive)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesResponse) SetCreatedAt(createdAt time.Time) {
	c.CreatedAt = createdAt
	c.require(createDocumentSeriesResponseFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDocumentSeriesResponse) SetUpdatedAt(updatedAt time.Time) {
	c.UpdatedAt = updatedAt
	c.require(createDocumentSeriesResponseFieldUpdatedAt)
}

func (c *CreateDocumentSeriesResponse) UnmarshalJSON(data []byte) error {
	type embed CreateDocumentSeriesResponse
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CreateDocumentSeriesResponse(unmarshaler.embed)
	c.CreatedAt = unmarshaler.CreatedAt.Time()
	c.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateDocumentSeriesResponse) MarshalJSON() ([]byte, error) {
	type embed CreateDocumentSeriesResponse
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed:     embed(*c),
		CreatedAt: internal.NewDateTime(c.CreatedAt),
		UpdatedAt: internal.NewDateTime(c.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateDocumentSeriesResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	deleteDocumentSeriesResponseFieldDeleted = big.NewInt(1 << 0)
)

type DeleteDocumentSeriesResponse struct {
	Deleted bool `json:"deleted" url:"deleted"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeleteDocumentSeriesResponse) GetDeleted() bool {
	if d == nil {
		return false
	}
	return d.Deleted
}

func (d *DeleteDocumentSeriesResponse) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeleteDocumentSeriesResponse) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetDeleted sets the Deleted field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteDocumentSeriesResponse) SetDeleted(deleted bool) {
	d.Deleted = deleted
	d.require(deleteDocumentSeriesResponseFieldDeleted)
}

func (d *DeleteDocumentSeriesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteDocumentSeriesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteDocumentSeriesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteDocumentSeriesResponse) MarshalJSON() ([]byte, error) {
	type embed DeleteDocumentSeriesResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeleteDocumentSeriesResponse) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	getDocumentSeriesResponseFieldID              = big.NewInt(1 << 0)
	getDocumentSeriesResponseFieldDocumentType    = big.NewInt(1 << 1)
	getDocumentSeriesResponseFieldPrefix          = big.NewInt(1 << 2)
	getDocumentSeriesResponseFieldName            = big.NewInt(1 << 3)
	getDocumentSeriesResponseFieldLabel           = big.NewInt(1 << 4)
	getDocumentSeriesResponseFieldOperationTypeID = big.NewInt(1 << 5)
	getDocumentSeriesResponseFieldNumberLength    = big.NewInt(1 << 6)
	getDocumentSeriesResponseFieldNextNumber      = big.NewInt(1 << 7)
	getDocumentSeriesResponseFieldAllocatedFrom   = big.NewInt(1 << 8)
	getDocumentSeriesResponseFieldAllocatedTo     = big.NewInt(1 << 9)
	getDocumentSeriesResponseFieldWarehouseID     = big.NewInt(1 << 10)
	getDocumentSeriesResponseFieldPrintSeries     = big.NewInt(1 << 11)
	getDocumentSeriesResponseFieldIsDefault       = big.NewInt(1 << 12)
	getDocumentSeriesResponseFieldIsActive        = big.NewInt(1 << 13)
	getDocumentSeriesResponseFieldCreatedAt       = big.NewInt(1 << 14)
	getDocumentSeriesResponseFieldUpdatedAt       = big.NewInt(1 << 15)
)

type GetDocumentSeriesResponse struct {
	ID              string    `json:"id" url:"id"`
	DocumentType    string    `json:"documentType" url:"documentType"`
	Prefix          string    `json:"prefix" url:"prefix"`
	Name            *string   `json:"name,omitempty" url:"name,omitempty"`
	Label           *string   `json:"label,omitempty" url:"label,omitempty"`
	OperationTypeID *string   `json:"operationTypeId,omitempty" url:"operationTypeId,omitempty"`
	NumberLength    int64     `json:"numberLength" url:"numberLength"`
	NextNumber      int64     `json:"nextNumber" url:"nextNumber"`
	AllocatedFrom   *int64    `json:"allocatedFrom,omitempty" url:"allocatedFrom,omitempty"`
	AllocatedTo     *int64    `json:"allocatedTo,omitempty" url:"allocatedTo,omitempty"`
	WarehouseID     *string   `json:"warehouseId,omitempty" url:"warehouseId,omitempty"`
	PrintSeries     bool      `json:"printSeries" url:"printSeries"`
	IsDefault       bool      `json:"isDefault" url:"isDefault"`
	IsActive        bool      `json:"isActive" url:"isActive"`
	CreatedAt       time.Time `json:"createdAt" url:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetDocumentSeriesResponse) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetDocumentSeriesResponse) GetDocumentType() string {
	if g == nil {
		return ""
	}
	return g.DocumentType
}

func (g *GetDocumentSeriesResponse) GetPrefix() string {
	if g == nil {
		return ""
	}
	return g.Prefix
}

func (g *GetDocumentSeriesResponse) GetName() *string {
	if g == nil {
		return nil
	}
	return g.Name
}

func (g *GetDocumentSeriesResponse) GetLabel() *string {
	if g == nil {
		return nil
	}
	return g.Label
}

func (g *GetDocumentSeriesResponse) GetOperationTypeID() *string {
	if g == nil {
		return nil
	}
	return g.OperationTypeID
}

func (g *GetDocumentSeriesResponse) GetNumberLength() int64 {
	if g == nil {
		return 0
	}
	return g.NumberLength
}

func (g *GetDocumentSeriesResponse) GetNextNumber() int64 {
	if g == nil {
		return 0
	}
	return g.NextNumber
}

func (g *GetDocumentSeriesResponse) GetAllocatedFrom() *int64 {
	if g == nil {
		return nil
	}
	return g.AllocatedFrom
}

func (g *GetDocumentSeriesResponse) GetAllocatedTo() *int64 {
	if g == nil {
		return nil
	}
	return g.AllocatedTo
}

func (g *GetDocumentSeriesResponse) GetWarehouseID() *string {
	if g == nil {
		return nil
	}
	return g.WarehouseID
}

func (g *GetDocumentSeriesResponse) GetPrintSeries() bool {
	if g == nil {
		return false
	}
	return g.PrintSeries
}

func (g *GetDocumentSeriesResponse) GetIsDefault() bool {
	if g == nil {
		return false
	}
	return g.IsDefault
}

func (g *GetDocumentSeriesResponse) GetIsActive() bool {
	if g == nil {
		return false
	}
	return g.IsActive
}

func (g *GetDocumentSeriesResponse) GetCreatedAt() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.CreatedAt
}

func (g *GetDocumentSeriesResponse) GetUpdatedAt() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.UpdatedAt
}

func (g *GetDocumentSeriesResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetDocumentSeriesResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDocumentSeriesResponse) SetID(id string) {
	g.ID = id
	g.require(getDocumentSeriesResponseFieldID)
}

// SetDocumentType sets the DocumentType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDocumentSeriesResponse) SetDocumentType(documentType string) {
	g.DocumentType = documentType
	g.require(getDocumentSeriesResponseFieldDocumentType)
}

// SetPrefix sets the Prefix field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDocumentSeriesResponse) SetPrefix(prefix string) {
	g.Prefix = prefix
	g.require(getDocumentSeriesResponseFieldPrefix)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDocumentSeriesResponse) SetName(name *string) {
	g.Name = name
	g.require(getDocumentSeriesResponseFieldName)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDocumentSeriesResponse) SetLabel(label *string) {
	g.Label = label
	g.require(getDocumentSeriesResponseFieldLabel)
}

// SetOperationTypeID sets the OperationTypeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDocumentSeriesResponse) SetOperationTypeID(operationTypeID *string) {
	g.OperationTypeID = operationTypeID
	g.require(getDocumentSeriesResponseFieldOperationTypeID)
}

// SetNumberLength sets the NumberLength field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDocumentSeriesResponse) SetNumberLength(numberLength int64) {
	g.NumberLength = numberLength
	g.require(getDocumentSeriesResponseFieldNumberLength)
}

// SetNextNumber sets the NextNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDocumentSeriesResponse) SetNextNumber(nextNumber int64) {
	g.NextNumber = nextNumber
	g.require(getDocumentSeriesResponseFieldNextNumber)
}

// SetAllocatedFrom sets the AllocatedFrom field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDocumentSeriesResponse) SetAllocatedFrom(allocatedFrom *int64) {
	g.AllocatedFrom = allocatedFrom
	g.require(getDocumentSeriesResponseFieldAllocatedFrom)
}

// SetAllocatedTo sets the AllocatedTo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDocumentSeriesResponse) SetAllocatedTo(allocatedTo *int64) {
	g.AllocatedTo = allocatedTo
	g.require(getDocumentSeriesResponseFieldAllocatedTo)
}

// SetWarehouseID sets the WarehouseID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDocumentSeriesResponse) SetWarehouseID(warehouseID *string) {
	g.WarehouseID = warehouseID
	g.require(getDocumentSeriesResponseFieldWarehouseID)
}

// SetPrintSeries sets the PrintSeries field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDocumentSeriesResponse) SetPrintSeries(printSeries bool) {
	g.PrintSeries = printSeries
	g.require(getDocumentSeriesResponseFieldPrintSeries)
}

// SetIsDefault sets the IsDefault field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDocumentSeriesResponse) SetIsDefault(isDefault bool) {
	g.IsDefault = isDefault
	g.require(getDocumentSeriesResponseFieldIsDefault)
}

// SetIsActive sets the IsActive field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDocumentSeriesResponse) SetIsActive(isActive bool) {
	g.IsActive = isActive
	g.require(getDocumentSeriesResponseFieldIsActive)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDocumentSeriesResponse) SetCreatedAt(createdAt time.Time) {
	g.CreatedAt = createdAt
	g.require(getDocumentSeriesResponseFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDocumentSeriesResponse) SetUpdatedAt(updatedAt time.Time) {
	g.UpdatedAt = updatedAt
	g.require(getDocumentSeriesResponseFieldUpdatedAt)
}

func (g *GetDocumentSeriesResponse) UnmarshalJSON(data []byte) error {
	type embed GetDocumentSeriesResponse
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*g),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*g = GetDocumentSeriesResponse(unmarshaler.embed)
	g.CreatedAt = unmarshaler.CreatedAt.Time()
	g.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetDocumentSeriesResponse) MarshalJSON() ([]byte, error) {
	type embed GetDocumentSeriesResponse
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed:     embed(*g),
		CreatedAt: internal.NewDateTime(g.CreatedAt),
		UpdatedAt: internal.NewDateTime(g.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetDocumentSeriesResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	listDocumentSeriesRequestFilterItemFieldField = big.NewInt(1 << 0)
	listDocumentSeriesRequestFilterItemFieldOp    = big.NewInt(1 << 1)
	listDocumentSeriesRequestFilterItemFieldValue = big.NewInt(1 << 2)
)

type ListDocumentSeriesRequestFilterItem struct {
	Field string                                    `json:"field" url:"field"`
	Op    ListDocumentSeriesRequestFilterItemOp     `json:"op" url:"op"`
	Value *ListDocumentSeriesRequestFilterItemValue `json:"value" url:"value"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListDocumentSeriesRequestFilterItem) GetField() string {
	if l == nil {
		return ""
	}
	return l.Field
}

func (l *ListDocumentSeriesRequestFilterItem) GetOp() ListDocumentSeriesRequestFilterItemOp {
	if l == nil {
		return ""
	}
	return l.Op
}

func (l *ListDocumentSeriesRequestFilterItem) GetValue() *ListDocumentSeriesRequestFilterItemValue {
	if l == nil {
		return nil
	}
	return l.Value
}

func (l *ListDocumentSeriesRequestFilterItem) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListDocumentSeriesRequestFilterItem) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetField sets the Field field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesRequestFilterItem) SetField(field string) {
	l.Field = field
	l.require(listDocumentSeriesRequestFilterItemFieldField)
}

// SetOp sets the Op field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesRequestFilterItem) SetOp(op ListDocumentSeriesRequestFilterItemOp) {
	l.Op = op
	l.require(listDocumentSeriesRequestFilterItemFieldOp)
}

// SetValue sets the Value field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesRequestFilterItem) SetValue(value *ListDocumentSeriesRequestFilterItemValue) {
	l.Value = value
	l.require(listDocumentSeriesRequestFilterItemFieldValue)
}

func (l *ListDocumentSeriesRequestFilterItem) UnmarshalJSON(data []byte) error {
	type unmarshaler ListDocumentSeriesRequestFilterItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListDocumentSeriesRequestFilterItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListDocumentSeriesRequestFilterItem) MarshalJSON() ([]byte, error) {
	type embed ListDocumentSeriesRequestFilterItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListDocumentSeriesRequestFilterItem) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

type ListDocumentSeriesRequestFilterItemOp string

const (
	ListDocumentSeriesRequestFilterItemOpEq       ListDocumentSeriesRequestFilterItemOp = "eq"
	ListDocumentSeriesRequestFilterItemOpNe       ListDocumentSeriesRequestFilterItemOp = "ne"
	ListDocumentSeriesRequestFilterItemOpContains ListDocumentSeriesRequestFilterItemOp = "contains"
	ListDocumentSeriesRequestFilterItemOpGte      ListDocumentSeriesRequestFilterItemOp = "gte"
	ListDocumentSeriesRequestFilterItemOpLte      ListDocumentSeriesRequestFilterItemOp = "lte"
	ListDocumentSeriesRequestFilterItemOpIn       ListDocumentSeriesRequestFilterItemOp = "in"
)

func NewListDocumentSeriesRequestFilterItemOpFromString(s string) (ListDocumentSeriesRequestFilterItemOp, error) {
	switch s {
	case "eq":
		return ListDocumentSeriesRequestFilterItemOpEq, nil
	case "ne":
		return ListDocumentSeriesRequestFilterItemOpNe, nil
	case "contains":
		return ListDocumentSeriesRequestFilterItemOpContains, nil
	case "gte":
		return ListDocumentSeriesRequestFilterItemOpGte, nil
	case "lte":
		return ListDocumentSeriesRequestFilterItemOpLte, nil
	case "in":
		return ListDocumentSeriesRequestFilterItemOpIn, nil
	}
	var t ListDocumentSeriesRequestFilterItemOp
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListDocumentSeriesRequestFilterItemOp) Ptr() *ListDocumentSeriesRequestFilterItemOp {
	return &l
}

type ListDocumentSeriesRequestFilterItemValue struct {
	String                                                string
	Double                                                float64
	Boolean                                               bool
	ListDocumentSeriesRequestFilterItemValueThreeItemList []*ListDocumentSeriesRequestFilterItemValueThreeItem

	typ string
}

func (l *ListDocumentSeriesRequestFilterItemValue) GetString() string {
	if l == nil {
		return ""
	}
	return l.String
}

func (l *ListDocumentSeriesRequestFilterItemValue) GetDouble() float64 {
	if l == nil {
		return 0
	}
	return l.Double
}

func (l *ListDocumentSeriesRequestFilterItemValue) GetBoolean() bool {
	if l == nil {
		return false
	}
	return l.Boolean
}

func (l *ListDocumentSeriesRequestFilterItemValue) GetListDocumentSeriesRequestFilterItemValueThreeItemList() []*ListDocumentSeriesRequestFilterItemValueThreeItem {
	if l == nil {
		return nil
	}
	return l.ListDocumentSeriesRequestFilterItemValueThreeItemList
}

func (l *ListDocumentSeriesRequestFilterItemValue) UnmarshalJSON(data []byte) error {
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		l.typ = "String"
		l.String = valueString
		return nil
	}
	var valueDouble float64
	if err := json.Unmarshal(data, &valueDouble); err == nil {
		l.typ = "Double"
		l.Double = valueDouble
		return nil
	}
	var valueBoolean bool
	if err := json.Unmarshal(data, &valueBoolean); err == nil {
		l.typ = "Boolean"
		l.Boolean = valueBoolean
		return nil
	}
	var valueListDocumentSeriesRequestFilterItemValueThreeItemList []*ListDocumentSeriesRequestFilterItemValueThreeItem
	if err := json.Unmarshal(data, &valueListDocumentSeriesRequestFilterItemValueThreeItemList); err == nil {
		l.typ = "ListDocumentSeriesRequestFilterItemValueThreeItemList"
		l.ListDocumentSeriesRequestFilterItemValueThreeItemList = valueListDocumentSeriesRequestFilterItemValueThreeItemList
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, l)
}

func (l ListDocumentSeriesRequestFilterItemValue) MarshalJSON() ([]byte, error) {
	if l.typ == "String" || l.String != "" {
		return json.Marshal(l.String)
	}
	if l.typ == "Double" || l.Double != 0 {
		return json.Marshal(l.Double)
	}
	if l.typ == "Boolean" || l.Boolean != false {
		return json.Marshal(l.Boolean)
	}
	if l.typ == "ListDocumentSeriesRequestFilterItemValueThreeItemList" || l.ListDocumentSeriesRequestFilterItemValueThreeItemList != nil {
		return json.Marshal(l.ListDocumentSeriesRequestFilterItemValueThreeItemList)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", l)
}

type ListDocumentSeriesRequestFilterItemValueVisitor interface {
	VisitString(string) error
	VisitDouble(float64) error
	VisitBoolean(bool) error
	VisitListDocumentSeriesRequestFilterItemValueThreeItemList([]*ListDocumentSeriesRequestFilterItemValueThreeItem) error
}

func (l *ListDocumentSeriesRequestFilterItemValue) Accept(visitor ListDocumentSeriesRequestFilterItemValueVisitor) error {
	if l.typ == "String" || l.String != "" {
		return visitor.VisitString(l.String)
	}
	if l.typ == "Double" || l.Double != 0 {
		return visitor.VisitDouble(l.Double)
	}
	if l.typ == "Boolean" || l.Boolean != false {
		return visitor.VisitBoolean(l.Boolean)
	}
	if l.typ == "ListDocumentSeriesRequestFilterItemValueThreeItemList" || l.ListDocumentSeriesRequestFilterItemValueThreeItemList != nil {
		return visitor.VisitListDocumentSeriesRequestFilterItemValueThreeItemList(l.ListDocumentSeriesRequestFilterItemValueThreeItemList)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", l)
}

type ListDocumentSeriesRequestFilterItemValueThreeItem struct {
	String string
	Double float64

	typ string
}

func (l *ListDocumentSeriesRequestFilterItemValueThreeItem) GetString() string {
	if l == nil {
		return ""
	}
	return l.String
}

func (l *ListDocumentSeriesRequestFilterItemValueThreeItem) GetDouble() float64 {
	if l == nil {
		return 0
	}
	return l.Double
}

func (l *ListDocumentSeriesRequestFilterItemValueThreeItem) UnmarshalJSON(data []byte) error {
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		l.typ = "String"
		l.String = valueString
		return nil
	}
	var valueDouble float64
	if err := json.Unmarshal(data, &valueDouble); err == nil {
		l.typ = "Double"
		l.Double = valueDouble
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, l)
}

func (l ListDocumentSeriesRequestFilterItemValueThreeItem) MarshalJSON() ([]byte, error) {
	if l.typ == "String" || l.String != "" {
		return json.Marshal(l.String)
	}
	if l.typ == "Double" || l.Double != 0 {
		return json.Marshal(l.Double)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", l)
}

type ListDocumentSeriesRequestFilterItemValueThreeItemVisitor interface {
	VisitString(string) error
	VisitDouble(float64) error
}

func (l *ListDocumentSeriesRequestFilterItemValueThreeItem) Accept(visitor ListDocumentSeriesRequestFilterItemValueThreeItemVisitor) error {
	if l.typ == "String" || l.String != "" {
		return visitor.VisitString(l.String)
	}
	if l.typ == "Double" || l.Double != 0 {
		return visitor.VisitDouble(l.Double)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", l)
}

var (
	listDocumentSeriesRequestSortItemFieldField = big.NewInt(1 << 0)
	listDocumentSeriesRequestSortItemFieldDir   = big.NewInt(1 << 1)
)

type ListDocumentSeriesRequestSortItem struct {
	Field string                                `json:"field" url:"field"`
	Dir   *ListDocumentSeriesRequestSortItemDir `json:"dir,omitempty" url:"dir,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListDocumentSeriesRequestSortItem) GetField() string {
	if l == nil {
		return ""
	}
	return l.Field
}

func (l *ListDocumentSeriesRequestSortItem) GetDir() *ListDocumentSeriesRequestSortItemDir {
	if l == nil {
		return nil
	}
	return l.Dir
}

func (l *ListDocumentSeriesRequestSortItem) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListDocumentSeriesRequestSortItem) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetField sets the Field field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesRequestSortItem) SetField(field string) {
	l.Field = field
	l.require(listDocumentSeriesRequestSortItemFieldField)
}

// SetDir sets the Dir field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesRequestSortItem) SetDir(dir *ListDocumentSeriesRequestSortItemDir) {
	l.Dir = dir
	l.require(listDocumentSeriesRequestSortItemFieldDir)
}

func (l *ListDocumentSeriesRequestSortItem) UnmarshalJSON(data []byte) error {
	type unmarshaler ListDocumentSeriesRequestSortItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListDocumentSeriesRequestSortItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListDocumentSeriesRequestSortItem) MarshalJSON() ([]byte, error) {
	type embed ListDocumentSeriesRequestSortItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListDocumentSeriesRequestSortItem) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

type ListDocumentSeriesRequestSortItemDir string

const (
	ListDocumentSeriesRequestSortItemDirAsc  ListDocumentSeriesRequestSortItemDir = "asc"
	ListDocumentSeriesRequestSortItemDirDesc ListDocumentSeriesRequestSortItemDir = "desc"
)

func NewListDocumentSeriesRequestSortItemDirFromString(s string) (ListDocumentSeriesRequestSortItemDir, error) {
	switch s {
	case "asc":
		return ListDocumentSeriesRequestSortItemDirAsc, nil
	case "desc":
		return ListDocumentSeriesRequestSortItemDirDesc, nil
	}
	var t ListDocumentSeriesRequestSortItemDir
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListDocumentSeriesRequestSortItemDir) Ptr() *ListDocumentSeriesRequestSortItemDir {
	return &l
}

var (
	listDocumentSeriesResponseFieldRows     = big.NewInt(1 << 0)
	listDocumentSeriesResponseFieldPage     = big.NewInt(1 << 1)
	listDocumentSeriesResponseFieldPageSize = big.NewInt(1 << 2)
	listDocumentSeriesResponseFieldTotal    = big.NewInt(1 << 3)
	listDocumentSeriesResponseFieldTotals   = big.NewInt(1 << 4)
)

type ListDocumentSeriesResponse struct {
	Rows     []*ListDocumentSeriesResponseRowsItem `json:"rows" url:"rows"`
	Page     int64                                 `json:"page" url:"page"`
	PageSize int64                                 `json:"pageSize" url:"pageSize"`
	Total    int64                                 `json:"total" url:"total"`
	Totals   map[string]string                     `json:"totals,omitempty" url:"totals,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListDocumentSeriesResponse) GetRows() []*ListDocumentSeriesResponseRowsItem {
	if l == nil {
		return nil
	}
	return l.Rows
}

func (l *ListDocumentSeriesResponse) GetPage() int64 {
	if l == nil {
		return 0
	}
	return l.Page
}

func (l *ListDocumentSeriesResponse) GetPageSize() int64 {
	if l == nil {
		return 0
	}
	return l.PageSize
}

func (l *ListDocumentSeriesResponse) GetTotal() int64 {
	if l == nil {
		return 0
	}
	return l.Total
}

func (l *ListDocumentSeriesResponse) GetTotals() map[string]string {
	if l == nil {
		return nil
	}
	return l.Totals
}

func (l *ListDocumentSeriesResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListDocumentSeriesResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetRows sets the Rows field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesResponse) SetRows(rows []*ListDocumentSeriesResponseRowsItem) {
	l.Rows = rows
	l.require(listDocumentSeriesResponseFieldRows)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesResponse) SetPage(page int64) {
	l.Page = page
	l.require(listDocumentSeriesResponseFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesResponse) SetPageSize(pageSize int64) {
	l.PageSize = pageSize
	l.require(listDocumentSeriesResponseFieldPageSize)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesResponse) SetTotal(total int64) {
	l.Total = total
	l.require(listDocumentSeriesResponseFieldTotal)
}

// SetTotals sets the Totals field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesResponse) SetTotals(totals map[string]string) {
	l.Totals = totals
	l.require(listDocumentSeriesResponseFieldTotals)
}

func (l *ListDocumentSeriesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListDocumentSeriesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListDocumentSeriesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListDocumentSeriesResponse) MarshalJSON() ([]byte, error) {
	type embed ListDocumentSeriesResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListDocumentSeriesResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	listDocumentSeriesResponseRowsItemFieldID              = big.NewInt(1 << 0)
	listDocumentSeriesResponseRowsItemFieldDocumentType    = big.NewInt(1 << 1)
	listDocumentSeriesResponseRowsItemFieldPrefix          = big.NewInt(1 << 2)
	listDocumentSeriesResponseRowsItemFieldName            = big.NewInt(1 << 3)
	listDocumentSeriesResponseRowsItemFieldLabel           = big.NewInt(1 << 4)
	listDocumentSeriesResponseRowsItemFieldOperationTypeID = big.NewInt(1 << 5)
	listDocumentSeriesResponseRowsItemFieldNumberLength    = big.NewInt(1 << 6)
	listDocumentSeriesResponseRowsItemFieldNextNumber      = big.NewInt(1 << 7)
	listDocumentSeriesResponseRowsItemFieldAllocatedFrom   = big.NewInt(1 << 8)
	listDocumentSeriesResponseRowsItemFieldAllocatedTo     = big.NewInt(1 << 9)
	listDocumentSeriesResponseRowsItemFieldWarehouseID     = big.NewInt(1 << 10)
	listDocumentSeriesResponseRowsItemFieldPrintSeries     = big.NewInt(1 << 11)
	listDocumentSeriesResponseRowsItemFieldIsDefault       = big.NewInt(1 << 12)
	listDocumentSeriesResponseRowsItemFieldIsActive        = big.NewInt(1 << 13)
	listDocumentSeriesResponseRowsItemFieldCreatedAt       = big.NewInt(1 << 14)
	listDocumentSeriesResponseRowsItemFieldUpdatedAt       = big.NewInt(1 << 15)
)

type ListDocumentSeriesResponseRowsItem struct {
	ID              string    `json:"id" url:"id"`
	DocumentType    string    `json:"documentType" url:"documentType"`
	Prefix          string    `json:"prefix" url:"prefix"`
	Name            *string   `json:"name,omitempty" url:"name,omitempty"`
	Label           *string   `json:"label,omitempty" url:"label,omitempty"`
	OperationTypeID *string   `json:"operationTypeId,omitempty" url:"operationTypeId,omitempty"`
	NumberLength    int64     `json:"numberLength" url:"numberLength"`
	NextNumber      int64     `json:"nextNumber" url:"nextNumber"`
	AllocatedFrom   *int64    `json:"allocatedFrom,omitempty" url:"allocatedFrom,omitempty"`
	AllocatedTo     *int64    `json:"allocatedTo,omitempty" url:"allocatedTo,omitempty"`
	WarehouseID     *string   `json:"warehouseId,omitempty" url:"warehouseId,omitempty"`
	PrintSeries     bool      `json:"printSeries" url:"printSeries"`
	IsDefault       bool      `json:"isDefault" url:"isDefault"`
	IsActive        bool      `json:"isActive" url:"isActive"`
	CreatedAt       time.Time `json:"createdAt" url:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListDocumentSeriesResponseRowsItem) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListDocumentSeriesResponseRowsItem) GetDocumentType() string {
	if l == nil {
		return ""
	}
	return l.DocumentType
}

func (l *ListDocumentSeriesResponseRowsItem) GetPrefix() string {
	if l == nil {
		return ""
	}
	return l.Prefix
}

func (l *ListDocumentSeriesResponseRowsItem) GetName() *string {
	if l == nil {
		return nil
	}
	return l.Name
}

func (l *ListDocumentSeriesResponseRowsItem) GetLabel() *string {
	if l == nil {
		return nil
	}
	return l.Label
}

func (l *ListDocumentSeriesResponseRowsItem) GetOperationTypeID() *string {
	if l == nil {
		return nil
	}
	return l.OperationTypeID
}

func (l *ListDocumentSeriesResponseRowsItem) GetNumberLength() int64 {
	if l == nil {
		return 0
	}
	return l.NumberLength
}

func (l *ListDocumentSeriesResponseRowsItem) GetNextNumber() int64 {
	if l == nil {
		return 0
	}
	return l.NextNumber
}

func (l *ListDocumentSeriesResponseRowsItem) GetAllocatedFrom() *int64 {
	if l == nil {
		return nil
	}
	return l.AllocatedFrom
}

func (l *ListDocumentSeriesResponseRowsItem) GetAllocatedTo() *int64 {
	if l == nil {
		return nil
	}
	return l.AllocatedTo
}

func (l *ListDocumentSeriesResponseRowsItem) GetWarehouseID() *string {
	if l == nil {
		return nil
	}
	return l.WarehouseID
}

func (l *ListDocumentSeriesResponseRowsItem) GetPrintSeries() bool {
	if l == nil {
		return false
	}
	return l.PrintSeries
}

func (l *ListDocumentSeriesResponseRowsItem) GetIsDefault() bool {
	if l == nil {
		return false
	}
	return l.IsDefault
}

func (l *ListDocumentSeriesResponseRowsItem) GetIsActive() bool {
	if l == nil {
		return false
	}
	return l.IsActive
}

func (l *ListDocumentSeriesResponseRowsItem) GetCreatedAt() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.CreatedAt
}

func (l *ListDocumentSeriesResponseRowsItem) GetUpdatedAt() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.UpdatedAt
}

func (l *ListDocumentSeriesResponseRowsItem) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListDocumentSeriesResponseRowsItem) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesResponseRowsItem) SetID(id string) {
	l.ID = id
	l.require(listDocumentSeriesResponseRowsItemFieldID)
}

// SetDocumentType sets the DocumentType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesResponseRowsItem) SetDocumentType(documentType string) {
	l.DocumentType = documentType
	l.require(listDocumentSeriesResponseRowsItemFieldDocumentType)
}

// SetPrefix sets the Prefix field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesResponseRowsItem) SetPrefix(prefix string) {
	l.Prefix = prefix
	l.require(listDocumentSeriesResponseRowsItemFieldPrefix)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesResponseRowsItem) SetName(name *string) {
	l.Name = name
	l.require(listDocumentSeriesResponseRowsItemFieldName)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesResponseRowsItem) SetLabel(label *string) {
	l.Label = label
	l.require(listDocumentSeriesResponseRowsItemFieldLabel)
}

// SetOperationTypeID sets the OperationTypeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesResponseRowsItem) SetOperationTypeID(operationTypeID *string) {
	l.OperationTypeID = operationTypeID
	l.require(listDocumentSeriesResponseRowsItemFieldOperationTypeID)
}

// SetNumberLength sets the NumberLength field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesResponseRowsItem) SetNumberLength(numberLength int64) {
	l.NumberLength = numberLength
	l.require(listDocumentSeriesResponseRowsItemFieldNumberLength)
}

// SetNextNumber sets the NextNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesResponseRowsItem) SetNextNumber(nextNumber int64) {
	l.NextNumber = nextNumber
	l.require(listDocumentSeriesResponseRowsItemFieldNextNumber)
}

// SetAllocatedFrom sets the AllocatedFrom field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesResponseRowsItem) SetAllocatedFrom(allocatedFrom *int64) {
	l.AllocatedFrom = allocatedFrom
	l.require(listDocumentSeriesResponseRowsItemFieldAllocatedFrom)
}

// SetAllocatedTo sets the AllocatedTo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesResponseRowsItem) SetAllocatedTo(allocatedTo *int64) {
	l.AllocatedTo = allocatedTo
	l.require(listDocumentSeriesResponseRowsItemFieldAllocatedTo)
}

// SetWarehouseID sets the WarehouseID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesResponseRowsItem) SetWarehouseID(warehouseID *string) {
	l.WarehouseID = warehouseID
	l.require(listDocumentSeriesResponseRowsItemFieldWarehouseID)
}

// SetPrintSeries sets the PrintSeries field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesResponseRowsItem) SetPrintSeries(printSeries bool) {
	l.PrintSeries = printSeries
	l.require(listDocumentSeriesResponseRowsItemFieldPrintSeries)
}

// SetIsDefault sets the IsDefault field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesResponseRowsItem) SetIsDefault(isDefault bool) {
	l.IsDefault = isDefault
	l.require(listDocumentSeriesResponseRowsItemFieldIsDefault)
}

// SetIsActive sets the IsActive field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesResponseRowsItem) SetIsActive(isActive bool) {
	l.IsActive = isActive
	l.require(listDocumentSeriesResponseRowsItemFieldIsActive)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesResponseRowsItem) SetCreatedAt(createdAt time.Time) {
	l.CreatedAt = createdAt
	l.require(listDocumentSeriesResponseRowsItemFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDocumentSeriesResponseRowsItem) SetUpdatedAt(updatedAt time.Time) {
	l.UpdatedAt = updatedAt
	l.require(listDocumentSeriesResponseRowsItemFieldUpdatedAt)
}

func (l *ListDocumentSeriesResponseRowsItem) UnmarshalJSON(data []byte) error {
	type embed ListDocumentSeriesResponseRowsItem
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*l),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*l = ListDocumentSeriesResponseRowsItem(unmarshaler.embed)
	l.CreatedAt = unmarshaler.CreatedAt.Time()
	l.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListDocumentSeriesResponseRowsItem) MarshalJSON() ([]byte, error) {
	type embed ListDocumentSeriesResponseRowsItem
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed:     embed(*l),
		CreatedAt: internal.NewDateTime(l.CreatedAt),
		UpdatedAt: internal.NewDateTime(l.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListDocumentSeriesResponseRowsItem) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

type UpdateDocumentSeriesRequestDocumentType string

const (
	UpdateDocumentSeriesRequestDocumentTypeSaleInvoice    UpdateDocumentSeriesRequestDocumentType = "sale_invoice"
	UpdateDocumentSeriesRequestDocumentTypeSaleCreditNote UpdateDocumentSeriesRequestDocumentType = "sale_credit_note"
	UpdateDocumentSeriesRequestDocumentTypeSaleProforma   UpdateDocumentSeriesRequestDocumentType = "sale_proforma"
	UpdateDocumentSeriesRequestDocumentTypeSaleAdvance    UpdateDocumentSeriesRequestDocumentType = "sale_advance"
)

func NewUpdateDocumentSeriesRequestDocumentTypeFromString(s string) (UpdateDocumentSeriesRequestDocumentType, error) {
	switch s {
	case "sale_invoice":
		return UpdateDocumentSeriesRequestDocumentTypeSaleInvoice, nil
	case "sale_credit_note":
		return UpdateDocumentSeriesRequestDocumentTypeSaleCreditNote, nil
	case "sale_proforma":
		return UpdateDocumentSeriesRequestDocumentTypeSaleProforma, nil
	case "sale_advance":
		return UpdateDocumentSeriesRequestDocumentTypeSaleAdvance, nil
	}
	var t UpdateDocumentSeriesRequestDocumentType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateDocumentSeriesRequestDocumentType) Ptr() *UpdateDocumentSeriesRequestDocumentType {
	return &u
}

var (
	updateDocumentSeriesResponseFieldID              = big.NewInt(1 << 0)
	updateDocumentSeriesResponseFieldDocumentType    = big.NewInt(1 << 1)
	updateDocumentSeriesResponseFieldPrefix          = big.NewInt(1 << 2)
	updateDocumentSeriesResponseFieldName            = big.NewInt(1 << 3)
	updateDocumentSeriesResponseFieldLabel           = big.NewInt(1 << 4)
	updateDocumentSeriesResponseFieldOperationTypeID = big.NewInt(1 << 5)
	updateDocumentSeriesResponseFieldNumberLength    = big.NewInt(1 << 6)
	updateDocumentSeriesResponseFieldNextNumber      = big.NewInt(1 << 7)
	updateDocumentSeriesResponseFieldAllocatedFrom   = big.NewInt(1 << 8)
	updateDocumentSeriesResponseFieldAllocatedTo     = big.NewInt(1 << 9)
	updateDocumentSeriesResponseFieldWarehouseID     = big.NewInt(1 << 10)
	updateDocumentSeriesResponseFieldPrintSeries     = big.NewInt(1 << 11)
	updateDocumentSeriesResponseFieldIsDefault       = big.NewInt(1 << 12)
	updateDocumentSeriesResponseFieldIsActive        = big.NewInt(1 << 13)
	updateDocumentSeriesResponseFieldCreatedAt       = big.NewInt(1 << 14)
	updateDocumentSeriesResponseFieldUpdatedAt       = big.NewInt(1 << 15)
)

type UpdateDocumentSeriesResponse struct {
	ID              string    `json:"id" url:"id"`
	DocumentType    string    `json:"documentType" url:"documentType"`
	Prefix          string    `json:"prefix" url:"prefix"`
	Name            *string   `json:"name,omitempty" url:"name,omitempty"`
	Label           *string   `json:"label,omitempty" url:"label,omitempty"`
	OperationTypeID *string   `json:"operationTypeId,omitempty" url:"operationTypeId,omitempty"`
	NumberLength    int64     `json:"numberLength" url:"numberLength"`
	NextNumber      int64     `json:"nextNumber" url:"nextNumber"`
	AllocatedFrom   *int64    `json:"allocatedFrom,omitempty" url:"allocatedFrom,omitempty"`
	AllocatedTo     *int64    `json:"allocatedTo,omitempty" url:"allocatedTo,omitempty"`
	WarehouseID     *string   `json:"warehouseId,omitempty" url:"warehouseId,omitempty"`
	PrintSeries     bool      `json:"printSeries" url:"printSeries"`
	IsDefault       bool      `json:"isDefault" url:"isDefault"`
	IsActive        bool      `json:"isActive" url:"isActive"`
	CreatedAt       time.Time `json:"createdAt" url:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateDocumentSeriesResponse) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateDocumentSeriesResponse) GetDocumentType() string {
	if u == nil {
		return ""
	}
	return u.DocumentType
}

func (u *UpdateDocumentSeriesResponse) GetPrefix() string {
	if u == nil {
		return ""
	}
	return u.Prefix
}

func (u *UpdateDocumentSeriesResponse) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateDocumentSeriesResponse) GetLabel() *string {
	if u == nil {
		return nil
	}
	return u.Label
}

func (u *UpdateDocumentSeriesResponse) GetOperationTypeID() *string {
	if u == nil {
		return nil
	}
	return u.OperationTypeID
}

func (u *UpdateDocumentSeriesResponse) GetNumberLength() int64 {
	if u == nil {
		return 0
	}
	return u.NumberLength
}

func (u *UpdateDocumentSeriesResponse) GetNextNumber() int64 {
	if u == nil {
		return 0
	}
	return u.NextNumber
}

func (u *UpdateDocumentSeriesResponse) GetAllocatedFrom() *int64 {
	if u == nil {
		return nil
	}
	return u.AllocatedFrom
}

func (u *UpdateDocumentSeriesResponse) GetAllocatedTo() *int64 {
	if u == nil {
		return nil
	}
	return u.AllocatedTo
}

func (u *UpdateDocumentSeriesResponse) GetWarehouseID() *string {
	if u == nil {
		return nil
	}
	return u.WarehouseID
}

func (u *UpdateDocumentSeriesResponse) GetPrintSeries() bool {
	if u == nil {
		return false
	}
	return u.PrintSeries
}

func (u *UpdateDocumentSeriesResponse) GetIsDefault() bool {
	if u == nil {
		return false
	}
	return u.IsDefault
}

func (u *UpdateDocumentSeriesResponse) GetIsActive() bool {
	if u == nil {
		return false
	}
	return u.IsActive
}

func (u *UpdateDocumentSeriesResponse) GetCreatedAt() time.Time {
	if u == nil {
		return time.Time{}
	}
	return u.CreatedAt
}

func (u *UpdateDocumentSeriesResponse) GetUpdatedAt() time.Time {
	if u == nil {
		return time.Time{}
	}
	return u.UpdatedAt
}

func (u *UpdateDocumentSeriesResponse) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UpdateDocumentSeriesResponse) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesResponse) SetID(id string) {
	u.ID = id
	u.require(updateDocumentSeriesResponseFieldID)
}

// SetDocumentType sets the DocumentType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesResponse) SetDocumentType(documentType string) {
	u.DocumentType = documentType
	u.require(updateDocumentSeriesResponseFieldDocumentType)
}

// SetPrefix sets the Prefix field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesResponse) SetPrefix(prefix string) {
	u.Prefix = prefix
	u.require(updateDocumentSeriesResponseFieldPrefix)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesResponse) SetName(name *string) {
	u.Name = name
	u.require(updateDocumentSeriesResponseFieldName)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesResponse) SetLabel(label *string) {
	u.Label = label
	u.require(updateDocumentSeriesResponseFieldLabel)
}

// SetOperationTypeID sets the OperationTypeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesResponse) SetOperationTypeID(operationTypeID *string) {
	u.OperationTypeID = operationTypeID
	u.require(updateDocumentSeriesResponseFieldOperationTypeID)
}

// SetNumberLength sets the NumberLength field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesResponse) SetNumberLength(numberLength int64) {
	u.NumberLength = numberLength
	u.require(updateDocumentSeriesResponseFieldNumberLength)
}

// SetNextNumber sets the NextNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesResponse) SetNextNumber(nextNumber int64) {
	u.NextNumber = nextNumber
	u.require(updateDocumentSeriesResponseFieldNextNumber)
}

// SetAllocatedFrom sets the AllocatedFrom field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesResponse) SetAllocatedFrom(allocatedFrom *int64) {
	u.AllocatedFrom = allocatedFrom
	u.require(updateDocumentSeriesResponseFieldAllocatedFrom)
}

// SetAllocatedTo sets the AllocatedTo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesResponse) SetAllocatedTo(allocatedTo *int64) {
	u.AllocatedTo = allocatedTo
	u.require(updateDocumentSeriesResponseFieldAllocatedTo)
}

// SetWarehouseID sets the WarehouseID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesResponse) SetWarehouseID(warehouseID *string) {
	u.WarehouseID = warehouseID
	u.require(updateDocumentSeriesResponseFieldWarehouseID)
}

// SetPrintSeries sets the PrintSeries field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesResponse) SetPrintSeries(printSeries bool) {
	u.PrintSeries = printSeries
	u.require(updateDocumentSeriesResponseFieldPrintSeries)
}

// SetIsDefault sets the IsDefault field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesResponse) SetIsDefault(isDefault bool) {
	u.IsDefault = isDefault
	u.require(updateDocumentSeriesResponseFieldIsDefault)
}

// SetIsActive sets the IsActive field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesResponse) SetIsActive(isActive bool) {
	u.IsActive = isActive
	u.require(updateDocumentSeriesResponseFieldIsActive)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesResponse) SetCreatedAt(createdAt time.Time) {
	u.CreatedAt = createdAt
	u.require(updateDocumentSeriesResponseFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesResponse) SetUpdatedAt(updatedAt time.Time) {
	u.UpdatedAt = updatedAt
	u.require(updateDocumentSeriesResponseFieldUpdatedAt)
}

func (u *UpdateDocumentSeriesResponse) UnmarshalJSON(data []byte) error {
	type embed UpdateDocumentSeriesResponse
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*u),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*u = UpdateDocumentSeriesResponse(unmarshaler.embed)
	u.CreatedAt = unmarshaler.CreatedAt.Time()
	u.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateDocumentSeriesResponse) MarshalJSON() ([]byte, error) {
	type embed UpdateDocumentSeriesResponse
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed:     embed(*u),
		CreatedAt: internal.NewDateTime(u.CreatedAt),
		UpdatedAt: internal.NewDateTime(u.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdateDocumentSeriesResponse) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	updateDocumentSeriesRequestFieldID              = big.NewInt(1 << 0)
	updateDocumentSeriesRequestFieldDocumentType    = big.NewInt(1 << 1)
	updateDocumentSeriesRequestFieldPrefix          = big.NewInt(1 << 2)
	updateDocumentSeriesRequestFieldName            = big.NewInt(1 << 3)
	updateDocumentSeriesRequestFieldLabel           = big.NewInt(1 << 4)
	updateDocumentSeriesRequestFieldOperationTypeID = big.NewInt(1 << 5)
	updateDocumentSeriesRequestFieldNumberLength    = big.NewInt(1 << 6)
	updateDocumentSeriesRequestFieldNextNumber      = big.NewInt(1 << 7)
	updateDocumentSeriesRequestFieldAllocatedFrom   = big.NewInt(1 << 8)
	updateDocumentSeriesRequestFieldAllocatedTo     = big.NewInt(1 << 9)
	updateDocumentSeriesRequestFieldWarehouseID     = big.NewInt(1 << 10)
	updateDocumentSeriesRequestFieldPrintSeries     = big.NewInt(1 << 11)
	updateDocumentSeriesRequestFieldIsDefault       = big.NewInt(1 << 12)
	updateDocumentSeriesRequestFieldIsActive        = big.NewInt(1 << 13)
)

type UpdateDocumentSeriesRequest struct {
	ID              string                                   `json:"id" url:"-"`
	DocumentType    *UpdateDocumentSeriesRequestDocumentType `json:"documentType,omitempty" url:"-"`
	Prefix          *string                                  `json:"prefix,omitempty" url:"-"`
	Name            *string                                  `json:"name,omitempty" url:"-"`
	Label           *string                                  `json:"label,omitempty" url:"-"`
	OperationTypeID *string                                  `json:"operationTypeId,omitempty" url:"-"`
	NumberLength    *int64                                   `json:"numberLength,omitempty" url:"-"`
	NextNumber      *int64                                   `json:"nextNumber,omitempty" url:"-"`
	AllocatedFrom   *int64                                   `json:"allocatedFrom,omitempty" url:"-"`
	AllocatedTo     *int64                                   `json:"allocatedTo,omitempty" url:"-"`
	WarehouseID     *string                                  `json:"warehouseId,omitempty" url:"-"`
	PrintSeries     *bool                                    `json:"printSeries,omitempty" url:"-"`
	IsDefault       *bool                                    `json:"isDefault,omitempty" url:"-"`
	IsActive        *bool                                    `json:"isActive,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateDocumentSeriesRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesRequest) SetID(id string) {
	u.ID = id
	u.require(updateDocumentSeriesRequestFieldID)
}

// SetDocumentType sets the DocumentType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesRequest) SetDocumentType(documentType *UpdateDocumentSeriesRequestDocumentType) {
	u.DocumentType = documentType
	u.require(updateDocumentSeriesRequestFieldDocumentType)
}

// SetPrefix sets the Prefix field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesRequest) SetPrefix(prefix *string) {
	u.Prefix = prefix
	u.require(updateDocumentSeriesRequestFieldPrefix)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesRequest) SetName(name *string) {
	u.Name = name
	u.require(updateDocumentSeriesRequestFieldName)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesRequest) SetLabel(label *string) {
	u.Label = label
	u.require(updateDocumentSeriesRequestFieldLabel)
}

// SetOperationTypeID sets the OperationTypeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesRequest) SetOperationTypeID(operationTypeID *string) {
	u.OperationTypeID = operationTypeID
	u.require(updateDocumentSeriesRequestFieldOperationTypeID)
}

// SetNumberLength sets the NumberLength field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesRequest) SetNumberLength(numberLength *int64) {
	u.NumberLength = numberLength
	u.require(updateDocumentSeriesRequestFieldNumberLength)
}

// SetNextNumber sets the NextNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesRequest) SetNextNumber(nextNumber *int64) {
	u.NextNumber = nextNumber
	u.require(updateDocumentSeriesRequestFieldNextNumber)
}

// SetAllocatedFrom sets the AllocatedFrom field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesRequest) SetAllocatedFrom(allocatedFrom *int64) {
	u.AllocatedFrom = allocatedFrom
	u.require(updateDocumentSeriesRequestFieldAllocatedFrom)
}

// SetAllocatedTo sets the AllocatedTo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesRequest) SetAllocatedTo(allocatedTo *int64) {
	u.AllocatedTo = allocatedTo
	u.require(updateDocumentSeriesRequestFieldAllocatedTo)
}

// SetWarehouseID sets the WarehouseID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesRequest) SetWarehouseID(warehouseID *string) {
	u.WarehouseID = warehouseID
	u.require(updateDocumentSeriesRequestFieldWarehouseID)
}

// SetPrintSeries sets the PrintSeries field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesRequest) SetPrintSeries(printSeries *bool) {
	u.PrintSeries = printSeries
	u.require(updateDocumentSeriesRequestFieldPrintSeries)
}

// SetIsDefault sets the IsDefault field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesRequest) SetIsDefault(isDefault *bool) {
	u.IsDefault = isDefault
	u.require(updateDocumentSeriesRequestFieldIsDefault)
}

// SetIsActive sets the IsActive field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDocumentSeriesRequest) SetIsActive(isActive *bool) {
	u.IsActive = isActive
	u.require(updateDocumentSeriesRequestFieldIsActive)
}

func (u *UpdateDocumentSeriesRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateDocumentSeriesRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateDocumentSeriesRequest(body)
	return nil
}

func (u *UpdateDocumentSeriesRequest) MarshalJSON() ([]byte, error) {
	type embed UpdateDocumentSeriesRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}
