// Code generated by Fern. DO NOT EDIT.

package nordlet

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/nordlet/nordlet-sdk-go/internal"
	big "math/big"
)

var (
	postV1PublicIntegrationRequestsRequestFieldIntegration = big.NewInt(1 << 0)
	postV1PublicIntegrationRequestsRequestFieldName        = big.NewInt(1 << 1)
	postV1PublicIntegrationRequestsRequestFieldCompany     = big.NewInt(1 << 2)
	postV1PublicIntegrationRequestsRequestFieldEmail       = big.NewInt(1 << 3)
	postV1PublicIntegrationRequestsRequestFieldDetails     = big.NewInt(1 << 4)
	postV1PublicIntegrationRequestsRequestFieldWebsite     = big.NewInt(1 << 5)
)

type PostV1PublicIntegrationRequestsRequest struct {
	Integration string  `json:"integration" url:"-"`
	Name        string  `json:"name" url:"-"`
	Company     *string `json:"company,omitempty" url:"-"`
	Email       string  `json:"email" url:"-"`
	Details     *string `json:"details,omitempty" url:"-"`
	Website     *string `json:"website,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PostV1PublicIntegrationRequestsRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetIntegration sets the Integration field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostV1PublicIntegrationRequestsRequest) SetIntegration(integration string) {
	p.Integration = integration
	p.require(postV1PublicIntegrationRequestsRequestFieldIntegration)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostV1PublicIntegrationRequestsRequest) SetName(name string) {
	p.Name = name
	p.require(postV1PublicIntegrationRequestsRequestFieldName)
}

// SetCompany sets the Company field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostV1PublicIntegrationRequestsRequest) SetCompany(company *string) {
	p.Company = company
	p.require(postV1PublicIntegrationRequestsRequestFieldCompany)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostV1PublicIntegrationRequestsRequest) SetEmail(email string) {
	p.Email = email
	p.require(postV1PublicIntegrationRequestsRequestFieldEmail)
}

// SetDetails sets the Details field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostV1PublicIntegrationRequestsRequest) SetDetails(details *string) {
	p.Details = details
	p.require(postV1PublicIntegrationRequestsRequestFieldDetails)
}

// SetWebsite sets the Website field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostV1PublicIntegrationRequestsRequest) SetWebsite(website *string) {
	p.Website = website
	p.require(postV1PublicIntegrationRequestsRequestFieldWebsite)
}

func (p *PostV1PublicIntegrationRequestsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler PostV1PublicIntegrationRequestsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*p = PostV1PublicIntegrationRequestsRequest(body)
	return nil
}

func (p *PostV1PublicIntegrationRequestsRequest) MarshalJSON() ([]byte, error) {
	type embed PostV1PublicIntegrationRequestsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	postV1PublicIntegrationRequestsResponseFieldReceived = big.NewInt(1 << 0)
)

type PostV1PublicIntegrationRequestsResponse struct {
	Received bool `json:"received" url:"received"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PostV1PublicIntegrationRequestsResponse) GetReceived() bool {
	if p == nil {
		return false
	}
	return p.Received
}

func (p *PostV1PublicIntegrationRequestsResponse) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PostV1PublicIntegrationRequestsResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetReceived sets the Received field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostV1PublicIntegrationRequestsResponse) SetReceived(received bool) {
	p.Received = received
	p.require(postV1PublicIntegrationRequestsResponseFieldReceived)
}

func (p *PostV1PublicIntegrationRequestsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PostV1PublicIntegrationRequestsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PostV1PublicIntegrationRequestsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PostV1PublicIntegrationRequestsResponse) MarshalJSON() ([]byte, error) {
	type embed PostV1PublicIntegrationRequestsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PostV1PublicIntegrationRequestsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}
