// Code generated by Fern. DO NOT EDIT.

package inventory

import (
	context "context"

	nordlet "github.com/nordlet/nordlet-sdk-go"
	core "github.com/nordlet/nordlet-sdk-go/core"
	internal "github.com/nordlet/nordlet-sdk-go/internal"
	option "github.com/nordlet/nordlet-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (c *Client) PostV1InventorySettingsGet(
	ctx context.Context,
	request *nordlet.PostV1InventorySettingsGetRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1InventorySettingsGetResponse, error) {
	response, err := c.WithRawResponse.PostV1InventorySettingsGet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1InventorySettingsUpdate(
	ctx context.Context,
	request *nordlet.PostV1InventorySettingsUpdateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1InventorySettingsUpdateResponse, error) {
	response, err := c.WithRawResponse.PostV1InventorySettingsUpdate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1InventoryWarehousesCreate(
	ctx context.Context,
	request *nordlet.PostV1InventoryWarehousesCreateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1InventoryWarehousesCreateResponse, error) {
	response, err := c.WithRawResponse.PostV1InventoryWarehousesCreate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1InventoryWarehousesList(
	ctx context.Context,
	request *nordlet.PostV1InventoryWarehousesListRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1InventoryWarehousesListResponse, error) {
	response, err := c.WithRawResponse.PostV1InventoryWarehousesList(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1InventoryStockReceive(
	ctx context.Context,
	request *nordlet.PostV1InventoryStockReceiveRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1InventoryStockReceiveResponse, error) {
	response, err := c.WithRawResponse.PostV1InventoryStockReceive(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1InventoryStockWriteOff(
	ctx context.Context,
	request *nordlet.PostV1InventoryStockWriteOffRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1InventoryStockWriteOffResponse, error) {
	response, err := c.WithRawResponse.PostV1InventoryStockWriteOff(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1InventoryStockTransfer(
	ctx context.Context,
	request *nordlet.PostV1InventoryStockTransferRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1InventoryStockTransferResponse, error) {
	response, err := c.WithRawResponse.PostV1InventoryStockTransfer(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1InventoryStockTake(
	ctx context.Context,
	request *nordlet.PostV1InventoryStockTakeRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1InventoryStockTakeResponse, error) {
	response, err := c.WithRawResponse.PostV1InventoryStockTake(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1InventoryStockLevels(
	ctx context.Context,
	request *nordlet.PostV1InventoryStockLevelsRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1InventoryStockLevelsResponse, error) {
	response, err := c.WithRawResponse.PostV1InventoryStockLevels(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1InventoryStockMovementsList(
	ctx context.Context,
	request *nordlet.PostV1InventoryStockMovementsListRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1InventoryStockMovementsListResponse, error) {
	response, err := c.WithRawResponse.PostV1InventoryStockMovementsList(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1InventoryLotsList(
	ctx context.Context,
	request *nordlet.PostV1InventoryLotsListRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1InventoryLotsListResponse, error) {
	response, err := c.WithRawResponse.PostV1InventoryLotsList(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1InventoryLotsGet(
	ctx context.Context,
	request *nordlet.PostV1InventoryLotsGetRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1InventoryLotsGetResponse, error) {
	response, err := c.WithRawResponse.PostV1InventoryLotsGet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1InventoryLotsUpdate(
	ctx context.Context,
	request *nordlet.PostV1InventoryLotsUpdateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1InventoryLotsUpdateResponse, error) {
	response, err := c.WithRawResponse.PostV1InventoryLotsUpdate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1InventoryLandedCostsCreate(
	ctx context.Context,
	request *nordlet.PostV1InventoryLandedCostsCreateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1InventoryLandedCostsCreateResponse, error) {
	response, err := c.WithRawResponse.PostV1InventoryLandedCostsCreate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1InventoryLandedCostsGet(
	ctx context.Context,
	request *nordlet.PostV1InventoryLandedCostsGetRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1InventoryLandedCostsGetResponse, error) {
	response, err := c.WithRawResponse.PostV1InventoryLandedCostsGet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1InventoryLandedCostsList(
	ctx context.Context,
	request *nordlet.PostV1InventoryLandedCostsListRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1InventoryLandedCostsListResponse, error) {
	response, err := c.WithRawResponse.PostV1InventoryLandedCostsList(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1InventoryReorderRulesCreate(
	ctx context.Context,
	request *nordlet.PostV1InventoryReorderRulesCreateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1InventoryReorderRulesCreateResponse, error) {
	response, err := c.WithRawResponse.PostV1InventoryReorderRulesCreate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1InventoryReorderRulesUpdate(
	ctx context.Context,
	request *nordlet.PostV1InventoryReorderRulesUpdateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1InventoryReorderRulesUpdateResponse, error) {
	response, err := c.WithRawResponse.PostV1InventoryReorderRulesUpdate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1InventoryReorderRulesDelete(
	ctx context.Context,
	request *nordlet.PostV1InventoryReorderRulesDeleteRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1InventoryReorderRulesDeleteResponse, error) {
	response, err := c.WithRawResponse.PostV1InventoryReorderRulesDelete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1InventoryReorderRulesList(
	ctx context.Context,
	request *nordlet.PostV1InventoryReorderRulesListRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1InventoryReorderRulesListResponse, error) {
	response, err := c.WithRawResponse.PostV1InventoryReorderRulesList(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1InventoryReorderRulesCheck(
	ctx context.Context,
	request *nordlet.PostV1InventoryReorderRulesCheckRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1InventoryReorderRulesCheckResponse, error) {
	response, err := c.WithRawResponse.PostV1InventoryReorderRulesCheck(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
