// Code generated by Fern. DO NOT EDIT.

package calendar

import (
	context "context"

	nordlet "github.com/nordlet/nordlet-sdk-go"
	core "github.com/nordlet/nordlet-sdk-go/core"
	internal "github.com/nordlet/nordlet-sdk-go/internal"
	option "github.com/nordlet/nordlet-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (c *Client) List(
	ctx context.Context,
	request *nordlet.ListCalendarRequest,
	opts ...option.RequestOption,
) (*nordlet.ListCalendarResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Get(
	ctx context.Context,
	request *nordlet.GetCalendarRequest,
	opts ...option.RequestOption,
) (*nordlet.GetCalendarResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// With amend: true the return is filed again as a correction of the one already submitted or accepted for the period; only returns whose format has a correction mark accept it.
func (c *Client) Submit(
	ctx context.Context,
	request *nordlet.SubmitCalendarRequest,
	opts ...option.RequestOption,
) (*nordlet.SubmitCalendarResponse, error) {
	response, err := c.WithRawResponse.Submit(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Builds the file of a deadline whose format Nordlet produces but whose administration takes it only through the company's own account or program. Nothing is sent and no filing is recorded.
func (c *Client) Download(
	ctx context.Context,
	request *nordlet.DownloadCalendarRequest,
	opts ...option.RequestOption,
) (*nordlet.DownloadCalendarResponse, error) {
	response, err := c.WithRawResponse.Download(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Create(
	ctx context.Context,
	request *nordlet.CreateCalendarRequest,
	opts ...option.RequestOption,
) (*nordlet.CreateCalendarResponse, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Update(
	ctx context.Context,
	request *nordlet.UpdateCalendarRequest,
	opts ...option.RequestOption,
) (*nordlet.UpdateCalendarResponse, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Delete(
	ctx context.Context,
	request *nordlet.DeleteCalendarRequest,
	opts ...option.RequestOption,
) (*nordlet.DeleteCalendarResponse, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
