// Code generated by Fern. DO NOT EDIT.

package reports

import (
	context "context"

	nordlet "github.com/nordlet/nordlet-sdk-go"
	core "github.com/nordlet/nordlet-sdk-go/core"
	internal "github.com/nordlet/nordlet-sdk-go/internal"
	option "github.com/nordlet/nordlet-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (c *Client) TrialBalance(
	ctx context.Context,
	request *nordlet.TrialBalanceReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.TrialBalanceReportsResponse, error) {
	response, err := c.WithRawResponse.TrialBalance(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) SizeCategory(
	ctx context.Context,
	request *nordlet.SizeCategoryReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.SizeCategoryReportsResponse, error) {
	response, err := c.WithRawResponse.SizeCategory(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) FinancialStatements(
	ctx context.Context,
	request *nordlet.FinancialStatementsReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.FinancialStatementsReportsResponse, error) {
	response, err := c.WithRawResponse.FinancialStatements(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GeneralJournal(
	ctx context.Context,
	request *nordlet.GeneralJournalReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.GeneralJournalReportsResponse, error) {
	response, err := c.WithRawResponse.GeneralJournal(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GlDetail(
	ctx context.Context,
	request *nordlet.GlDetailReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.GlDetailReportsResponse, error) {
	response, err := c.WithRawResponse.GlDetail(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PartnerBalances(
	ctx context.Context,
	request *nordlet.PartnerBalancesReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.PartnerBalancesReportsResponse, error) {
	response, err := c.WithRawResponse.PartnerBalances(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) DebtAging(
	ctx context.Context,
	request *nordlet.DebtAgingReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.DebtAgingReportsResponse, error) {
	response, err := c.WithRawResponse.DebtAging(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) MonthlySummary(
	ctx context.Context,
	request *nordlet.MonthlySummaryReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.MonthlySummaryReportsResponse, error) {
	response, err := c.WithRawResponse.MonthlySummary(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) StockBalance(
	ctx context.Context,
	request *nordlet.StockBalanceReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.StockBalanceReportsResponse, error) {
	response, err := c.WithRawResponse.StockBalance(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) StockMovement(
	ctx context.Context,
	request *nordlet.StockMovementReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.StockMovementReportsResponse, error) {
	response, err := c.WithRawResponse.StockMovement(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) VatSummary(
	ctx context.Context,
	request *nordlet.VatSummaryReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.VatSummaryReportsResponse, error) {
	response, err := c.WithRawResponse.VatSummary(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CashFlow(
	ctx context.Context,
	request *nordlet.CashFlowReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.CashFlowReportsResponse, error) {
	response, err := c.WithRawResponse.CashFlow(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) StockAging(
	ctx context.Context,
	request *nordlet.StockAgingReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.StockAgingReportsResponse, error) {
	response, err := c.WithRawResponse.StockAging(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) StockShortage(
	ctx context.Context,
	request *nordlet.StockShortageReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.StockShortageReportsResponse, error) {
	response, err := c.WithRawResponse.StockShortage(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Export the ledger of one financial year as an SIE file (the Swedish standard accounting interchange format, specification 4B). The file carries the chart of accounts, the opening and closing balance of every balance sheet account and the turnover of every result account for the year and the year before it, and, when asked for, every posted voucher of the year with its lines. Cost centres travel as dimension 1 and projects as dimension 6. Services that build a Swedish annual report read this file.
func (c *Client) Sie(
	ctx context.Context,
	request *nordlet.SieReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.SieReportsResponse, error) {
	response, err := c.WithRawResponse.Sie(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Export the posted ledger of a period as a DATEV Buchungsstapel file (DATEV format, category 21, version 700). Every transaction becomes one or more bookings of an amount between an account and a contra account; a transaction with more than two lines is split into pairs whose totals match it. The file is semicolon separated and written in the Windows-1252 character set DATEV expects.
func (c *Client) Datev(
	ctx context.Context,
	request *nordlet.DatevReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.DatevReportsResponse, error) {
	response, err := c.WithRawResponse.Datev(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Export the posted ledger of a period as a French FEC file (fichier des écritures comptables, order of 29 July 2013). One line per journal entry line, with the eighteen fields the order names, in their order, after a header line. Tab separated, UTF-8, comma as the decimal separator.
func (c *Client) Fec(
	ctx context.Context,
	request *nordlet.FecReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.FecReportsResponse, error) {
	response, err := c.WithRawResponse.Fec(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) EuPurchases(
	ctx context.Context,
	request *nordlet.EuPurchasesReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.EuPurchasesReportsResponse, error) {
	response, err := c.WithRawResponse.EuPurchases(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) VatDetail(
	ctx context.Context,
	request *nordlet.VatDetailReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.VatDetailReportsResponse, error) {
	response, err := c.WithRawResponse.VatDetail(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PosSales(
	ctx context.Context,
	request *nordlet.PosSalesReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.PosSalesReportsResponse, error) {
	response, err := c.WithRawResponse.PosSales(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) OnlineSales(
	ctx context.Context,
	request *nordlet.OnlineSalesReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.OnlineSalesReportsResponse, error) {
	response, err := c.WithRawResponse.OnlineSales(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Oss(
	ctx context.Context,
	request *nordlet.OssReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.OssReportsResponse, error) {
	response, err := c.WithRawResponse.Oss(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) AdvanceReconciliation(
	ctx context.Context,
	request *nordlet.AdvanceReconciliationReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.AdvanceReconciliationReportsResponse, error) {
	response, err := c.WithRawResponse.AdvanceReconciliation(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) WriteOffActs(
	ctx context.Context,
	request *nordlet.WriteOffActsReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.WriteOffActsReportsResponse, error) {
	response, err := c.WithRawResponse.WriteOffActs(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CostCenters(
	ctx context.Context,
	request *nordlet.CostCentersReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.CostCentersReportsResponse, error) {
	response, err := c.WithRawResponse.CostCenters(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CostCenterActivity(
	ctx context.Context,
	request *nordlet.CostCenterActivityReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.CostCenterActivityReportsResponse, error) {
	response, err := c.WithRawResponse.CostCenterActivity(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CostCenterItems(
	ctx context.Context,
	request *nordlet.CostCenterItemsReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.CostCenterItemsReportsResponse, error) {
	response, err := c.WithRawResponse.CostCenterItems(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) JobsCreate(
	ctx context.Context,
	request *nordlet.JobsCreateReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.JobsCreateReportsResponse, error) {
	response, err := c.WithRawResponse.JobsCreate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) JobsGet(
	ctx context.Context,
	request *nordlet.JobsGetReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.JobsGetReportsResponse, error) {
	response, err := c.WithRawResponse.JobsGet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) JobsList(
	ctx context.Context,
	request *nordlet.JobsListReportsRequest,
	opts ...option.RequestOption,
) (*nordlet.JobsListReportsResponse, error) {
	response, err := c.WithRawResponse.JobsList(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
