// Code generated by Fern. DO NOT EDIT.

package reports

import (
	context "context"

	nordlet "github.com/nordlet/nordlet-sdk-go"
	core "github.com/nordlet/nordlet-sdk-go/core"
	internal "github.com/nordlet/nordlet-sdk-go/internal"
	option "github.com/nordlet/nordlet-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (c *Client) PostV1ReportsTrialBalance(
	ctx context.Context,
	request *nordlet.PostV1ReportsTrialBalanceRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ReportsTrialBalanceResponse, error) {
	response, err := c.WithRawResponse.PostV1ReportsTrialBalance(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ReportsSizeCategory(
	ctx context.Context,
	request *nordlet.PostV1ReportsSizeCategoryRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ReportsSizeCategoryResponse, error) {
	response, err := c.WithRawResponse.PostV1ReportsSizeCategory(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ReportsFinancialStatements(
	ctx context.Context,
	request *nordlet.PostV1ReportsFinancialStatementsRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ReportsFinancialStatementsResponse, error) {
	response, err := c.WithRawResponse.PostV1ReportsFinancialStatements(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ReportsGeneralJournal(
	ctx context.Context,
	request *nordlet.PostV1ReportsGeneralJournalRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ReportsGeneralJournalResponse, error) {
	response, err := c.WithRawResponse.PostV1ReportsGeneralJournal(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ReportsGlDetail(
	ctx context.Context,
	request *nordlet.PostV1ReportsGlDetailRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ReportsGlDetailResponse, error) {
	response, err := c.WithRawResponse.PostV1ReportsGlDetail(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ReportsPartnerBalances(
	ctx context.Context,
	request *nordlet.PostV1ReportsPartnerBalancesRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ReportsPartnerBalancesResponse, error) {
	response, err := c.WithRawResponse.PostV1ReportsPartnerBalances(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ReportsDebtAging(
	ctx context.Context,
	request *nordlet.PostV1ReportsDebtAgingRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ReportsDebtAgingResponse, error) {
	response, err := c.WithRawResponse.PostV1ReportsDebtAging(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ReportsMonthlySummary(
	ctx context.Context,
	request *nordlet.PostV1ReportsMonthlySummaryRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ReportsMonthlySummaryResponse, error) {
	response, err := c.WithRawResponse.PostV1ReportsMonthlySummary(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ReportsStockBalance(
	ctx context.Context,
	request *nordlet.PostV1ReportsStockBalanceRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ReportsStockBalanceResponse, error) {
	response, err := c.WithRawResponse.PostV1ReportsStockBalance(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ReportsStockMovement(
	ctx context.Context,
	request *nordlet.PostV1ReportsStockMovementRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ReportsStockMovementResponse, error) {
	response, err := c.WithRawResponse.PostV1ReportsStockMovement(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ReportsVatSummary(
	ctx context.Context,
	request *nordlet.PostV1ReportsVatSummaryRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ReportsVatSummaryResponse, error) {
	response, err := c.WithRawResponse.PostV1ReportsVatSummary(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ReportsCashFlow(
	ctx context.Context,
	request *nordlet.PostV1ReportsCashFlowRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ReportsCashFlowResponse, error) {
	response, err := c.WithRawResponse.PostV1ReportsCashFlow(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ReportsStockAging(
	ctx context.Context,
	request *nordlet.PostV1ReportsStockAgingRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ReportsStockAgingResponse, error) {
	response, err := c.WithRawResponse.PostV1ReportsStockAging(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ReportsStockShortage(
	ctx context.Context,
	request *nordlet.PostV1ReportsStockShortageRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ReportsStockShortageResponse, error) {
	response, err := c.WithRawResponse.PostV1ReportsStockShortage(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ReportsEuPurchases(
	ctx context.Context,
	request *nordlet.PostV1ReportsEuPurchasesRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ReportsEuPurchasesResponse, error) {
	response, err := c.WithRawResponse.PostV1ReportsEuPurchases(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ReportsVatDetail(
	ctx context.Context,
	request *nordlet.PostV1ReportsVatDetailRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ReportsVatDetailResponse, error) {
	response, err := c.WithRawResponse.PostV1ReportsVatDetail(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ReportsPosSales(
	ctx context.Context,
	request *nordlet.PostV1ReportsPosSalesRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ReportsPosSalesResponse, error) {
	response, err := c.WithRawResponse.PostV1ReportsPosSales(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ReportsOnlineSales(
	ctx context.Context,
	request *nordlet.PostV1ReportsOnlineSalesRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ReportsOnlineSalesResponse, error) {
	response, err := c.WithRawResponse.PostV1ReportsOnlineSales(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ReportsOss(
	ctx context.Context,
	request *nordlet.PostV1ReportsOssRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ReportsOssResponse, error) {
	response, err := c.WithRawResponse.PostV1ReportsOss(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ReportsAdvanceReconciliation(
	ctx context.Context,
	request *nordlet.PostV1ReportsAdvanceReconciliationRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ReportsAdvanceReconciliationResponse, error) {
	response, err := c.WithRawResponse.PostV1ReportsAdvanceReconciliation(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ReportsWriteOffActs(
	ctx context.Context,
	request *nordlet.PostV1ReportsWriteOffActsRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ReportsWriteOffActsResponse, error) {
	response, err := c.WithRawResponse.PostV1ReportsWriteOffActs(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ReportsCostCenters(
	ctx context.Context,
	request *nordlet.PostV1ReportsCostCentersRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ReportsCostCentersResponse, error) {
	response, err := c.WithRawResponse.PostV1ReportsCostCenters(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ReportsCostCenterActivity(
	ctx context.Context,
	request *nordlet.PostV1ReportsCostCenterActivityRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ReportsCostCenterActivityResponse, error) {
	response, err := c.WithRawResponse.PostV1ReportsCostCenterActivity(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ReportsCostCenterItems(
	ctx context.Context,
	request *nordlet.PostV1ReportsCostCenterItemsRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ReportsCostCenterItemsResponse, error) {
	response, err := c.WithRawResponse.PostV1ReportsCostCenterItems(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ReportsJobsCreate(
	ctx context.Context,
	request *nordlet.PostV1ReportsJobsCreateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ReportsJobsCreateResponse, error) {
	response, err := c.WithRawResponse.PostV1ReportsJobsCreate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ReportsJobsGet(
	ctx context.Context,
	request *nordlet.PostV1ReportsJobsGetRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ReportsJobsGetResponse, error) {
	response, err := c.WithRawResponse.PostV1ReportsJobsGet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1ReportsJobsList(
	ctx context.Context,
	request *nordlet.PostV1ReportsJobsListRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1ReportsJobsListResponse, error) {
	response, err := c.WithRawResponse.PostV1ReportsJobsList(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
