// Code generated by Fern. DO NOT EDIT.

package ledger_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	nordlet "github.com/nordlet/nordlet-sdk-go"
	client "github.com/nordlet/nordlet-sdk-go/client"
	option "github.com/nordlet/nordlet-sdk-go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestLedgerAccountsListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.AccountsListLedgerRequest{}
	_, invocationErr := client.Ledger.AccountsList(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLedgerAccountsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLedgerAccountsListWithWireMock", "POST", "/v1/ledger/accounts/list", nil, 1)
}

func TestLedgerAccountsCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.AccountsCreateLedgerRequest{
		Code: "code",
		Name: "name",
		Type: nordlet.AccountsCreateLedgerRequestTypeAsset,
	}
	_, invocationErr := client.Ledger.AccountsCreate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLedgerAccountsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLedgerAccountsCreateWithWireMock", "POST", "/v1/ledger/accounts/create", nil, 1)
}

func TestLedgerAccountsUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.AccountsUpdateLedgerRequest{
		ID: "id",
	}
	_, invocationErr := client.Ledger.AccountsUpdate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLedgerAccountsUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLedgerAccountsUpdateWithWireMock", "POST", "/v1/ledger/accounts/update", nil, 1)
}

func TestLedgerAccountsApplyTemplateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.AccountsApplyTemplateLedgerRequest{}
	_, invocationErr := client.Ledger.AccountsApplyTemplate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLedgerAccountsApplyTemplateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLedgerAccountsApplyTemplateWithWireMock", "POST", "/v1/ledger/accounts/apply-template", nil, 1)
}

func TestLedgerAccountsSwitchChartWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.AccountsSwitchChartLedgerRequest{}
	_, invocationErr := client.Ledger.AccountsSwitchChart(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLedgerAccountsSwitchChartWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLedgerAccountsSwitchChartWithWireMock", "POST", "/v1/ledger/accounts/switch-chart", nil, 1)
}

func TestLedgerPeriodsListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PeriodsListLedgerRequest{}
	_, invocationErr := client.Ledger.PeriodsList(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLedgerPeriodsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLedgerPeriodsListWithWireMock", "POST", "/v1/ledger/periods/list", nil, 1)
}

func TestLedgerPeriodsLockWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PeriodsLockLedgerRequest{
		Year:  int64(1000000),
		Month: int64(1000000),
	}
	_, invocationErr := client.Ledger.PeriodsLock(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLedgerPeriodsLockWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLedgerPeriodsLockWithWireMock", "POST", "/v1/ledger/periods/lock", nil, 1)
}

func TestLedgerPeriodsUnlockWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PeriodsUnlockLedgerRequest{
		Year:  int64(1000000),
		Month: int64(1000000),
	}
	_, invocationErr := client.Ledger.PeriodsUnlock(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLedgerPeriodsUnlockWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLedgerPeriodsUnlockWithWireMock", "POST", "/v1/ledger/periods/unlock", nil, 1)
}

func TestLedgerJournalTransactionsListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.JournalTransactionsListLedgerRequest{}
	_, invocationErr := client.Ledger.JournalTransactionsList(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLedgerJournalTransactionsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLedgerJournalTransactionsListWithWireMock", "POST", "/v1/ledger/journal/transactions/list", nil, 1)
}

func TestLedgerCostCentersCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.CostCentersCreateLedgerRequest{
		Code: "code",
		Name: "name",
	}
	_, invocationErr := client.Ledger.CostCentersCreate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLedgerCostCentersCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLedgerCostCentersCreateWithWireMock", "POST", "/v1/ledger/cost-centers/create", nil, 1)
}

func TestLedgerCostCentersUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.CostCentersUpdateLedgerRequest{
		ID: "id",
	}
	_, invocationErr := client.Ledger.CostCentersUpdate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLedgerCostCentersUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLedgerCostCentersUpdateWithWireMock", "POST", "/v1/ledger/cost-centers/update", nil, 1)
}

func TestLedgerCostCentersListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.CostCentersListLedgerRequest{}
	_, invocationErr := client.Ledger.CostCentersList(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLedgerCostCentersListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLedgerCostCentersListWithWireMock", "POST", "/v1/ledger/cost-centers/list", nil, 1)
}

func TestLedgerCostCenterGroupsCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.CostCenterGroupsCreateLedgerRequest{
		Code: "code",
		Name: "name",
	}
	_, invocationErr := client.Ledger.CostCenterGroupsCreate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLedgerCostCenterGroupsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLedgerCostCenterGroupsCreateWithWireMock", "POST", "/v1/ledger/cost-center-groups/create", nil, 1)
}

func TestLedgerCostCenterGroupsUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.CostCenterGroupsUpdateLedgerRequest{
		ID: "id",
	}
	_, invocationErr := client.Ledger.CostCenterGroupsUpdate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLedgerCostCenterGroupsUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLedgerCostCenterGroupsUpdateWithWireMock", "POST", "/v1/ledger/cost-center-groups/update", nil, 1)
}

func TestLedgerCostCenterGroupsDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.CostCenterGroupsDeleteLedgerRequest{
		ID: "id",
	}
	_, invocationErr := client.Ledger.CostCenterGroupsDelete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLedgerCostCenterGroupsDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLedgerCostCenterGroupsDeleteWithWireMock", "POST", "/v1/ledger/cost-center-groups/delete", nil, 1)
}

func TestLedgerCostCenterGroupsListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.CostCenterGroupsListLedgerRequest{}
	_, invocationErr := client.Ledger.CostCenterGroupsList(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLedgerCostCenterGroupsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLedgerCostCenterGroupsListWithWireMock", "POST", "/v1/ledger/cost-center-groups/list", nil, 1)
}

func TestLedgerPostingRulesListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostingRulesListLedgerRequest{}
	_, invocationErr := client.Ledger.PostingRulesList(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLedgerPostingRulesListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLedgerPostingRulesListWithWireMock", "POST", "/v1/ledger/posting-rules/list", nil, 1)
}

func TestLedgerPostingRulesUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.PostingRulesUpdateLedgerRequest{
		Rules: []*nordlet.PostingRulesUpdateLedgerRequestRulesItem{
			&nordlet.PostingRulesUpdateLedgerRequestRulesItem{
				Key: nordlet.PostingRulesUpdateLedgerRequestRulesItemKeySalesReceivable,
			},
		},
	}
	_, invocationErr := client.Ledger.PostingRulesUpdate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLedgerPostingRulesUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLedgerPostingRulesUpdateWithWireMock", "POST", "/v1/ledger/posting-rules/update", nil, 1)
}

func TestLedgerOwnersCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.OwnersCreateLedgerRequest{
		Name: "name",
	}
	_, invocationErr := client.Ledger.OwnersCreate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLedgerOwnersCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLedgerOwnersCreateWithWireMock", "POST", "/v1/ledger/owners/create", nil, 1)
}

func TestLedgerOwnersUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.OwnersUpdateLedgerRequest{
		ID: "id",
	}
	_, invocationErr := client.Ledger.OwnersUpdate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLedgerOwnersUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLedgerOwnersUpdateWithWireMock", "POST", "/v1/ledger/owners/update", nil, 1)
}

func TestLedgerOwnersDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.OwnersDeleteLedgerRequest{
		ID: "id",
	}
	_, invocationErr := client.Ledger.OwnersDelete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLedgerOwnersDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLedgerOwnersDeleteWithWireMock", "POST", "/v1/ledger/owners/delete", nil, 1)
}

func TestLedgerOwnersListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.OwnersListLedgerRequest{}
	_, invocationErr := client.Ledger.OwnersList(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLedgerOwnersListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLedgerOwnersListWithWireMock", "POST", "/v1/ledger/owners/list", nil, 1)
}

func TestLedgerJournalTransactionsGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.JournalTransactionsGetLedgerRequest{
		ID: "id",
	}
	_, invocationErr := client.Ledger.JournalTransactionsGet(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLedgerJournalTransactionsGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLedgerJournalTransactionsGetWithWireMock", "POST", "/v1/ledger/journal/transactions/get", nil, 1)
}

func TestLedgerJournalTransactionsCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.JournalTransactionsCreateLedgerRequest{
		Date: nordlet.MustParseDate(
			"2026-07-01",
		),
		Entries: []*nordlet.JournalTransactionsCreateLedgerRequestEntriesItem{
			&nordlet.JournalTransactionsCreateLedgerRequestEntriesItem{
				AccountCode: "accountCode",
			},
		},
	}
	_, invocationErr := client.Ledger.JournalTransactionsCreate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLedgerJournalTransactionsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLedgerJournalTransactionsCreateWithWireMock", "POST", "/v1/ledger/journal/transactions/create", nil, 1)
}

func TestLedgerStatementRowsSchemesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.StatementRowsSchemesLedgerRequest{}
	_, invocationErr := client.Ledger.StatementRowsSchemes(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLedgerStatementRowsSchemesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLedgerStatementRowsSchemesWithWireMock", "POST", "/v1/ledger/statement-rows/schemes", nil, 1)
}

func TestLedgerStatementRowsListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.StatementRowsListLedgerRequest{
		Scheme: "scheme",
	}
	_, invocationErr := client.Ledger.StatementRowsList(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLedgerStatementRowsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLedgerStatementRowsListWithWireMock", "POST", "/v1/ledger/statement-rows/list", nil, 1)
}

func TestLedgerStatementRowsSetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &nordlet.StatementRowsSetLedgerRequest{
		Scheme:      "scheme",
		AccountCode: "accountCode",
	}
	_, invocationErr := client.Ledger.StatementRowsSet(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLedgerStatementRowsSetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLedgerStatementRowsSetWithWireMock", "POST", "/v1/ledger/statement-rows/set", nil, 1)
}
