// Code generated by Fern. DO NOT EDIT.

package cash

import (
	context "context"

	nordlet "github.com/nordlet/nordlet-sdk-go"
	core "github.com/nordlet/nordlet-sdk-go/core"
	internal "github.com/nordlet/nordlet-sdk-go/internal"
	option "github.com/nordlet/nordlet-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (c *Client) OrdersCreate(
	ctx context.Context,
	request *nordlet.OrdersCreateCashRequest,
	opts ...option.RequestOption,
) (*nordlet.OrdersCreateCashResponse, error) {
	response, err := c.WithRawResponse.OrdersCreate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) OrdersGet(
	ctx context.Context,
	request *nordlet.OrdersGetCashRequest,
	opts ...option.RequestOption,
) (*nordlet.OrdersGetCashResponse, error) {
	response, err := c.WithRawResponse.OrdersGet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) OrdersList(
	ctx context.Context,
	request *nordlet.OrdersListCashRequest,
	opts ...option.RequestOption,
) (*nordlet.OrdersListCashResponse, error) {
	response, err := c.WithRawResponse.OrdersList(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Balance(
	ctx context.Context,
	request *nordlet.BalanceCashRequest,
	opts ...option.RequestOption,
) (*nordlet.BalanceCashResponse, error) {
	response, err := c.WithRawResponse.Balance(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) AdvanceHoldersBalances(
	ctx context.Context,
	request *nordlet.AdvanceHoldersBalancesCashRequest,
	opts ...option.RequestOption,
) (*nordlet.AdvanceHoldersBalancesCashResponse, error) {
	response, err := c.WithRawResponse.AdvanceHoldersBalances(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
