// Code generated by Fern. DO NOT EDIT.

package account

import (
	context "context"
	http "net/http"

	nordlet "github.com/nordlet/nordlet-sdk-go"
	core "github.com/nordlet/nordlet-sdk-go/core"
	internal "github.com/nordlet/nordlet-sdk-go/internal"
	option "github.com/nordlet/nordlet-sdk-go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) LoginLinkRequest(
	ctx context.Context,
	request *nordlet.LoginLinkRequestAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.LoginLinkRequestAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/login-link/request"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.LoginLinkRequestAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.LoginLinkRequestAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) LoginLinkConsume(
	ctx context.Context,
	request *nordlet.LoginLinkConsumeAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.LoginLinkConsumeAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/login-link/consume"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.LoginLinkConsumeAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.LoginLinkConsumeAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Logout(
	ctx context.Context,
	request *nordlet.LogoutAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.LogoutAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/logout"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.LogoutAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.LogoutAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Me(
	ctx context.Context,
	request *nordlet.MeAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.MeAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/me"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.MeAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.MeAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) MembersList(
	ctx context.Context,
	request *nordlet.MembersListAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.MembersListAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/members/list"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.MembersListAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.MembersListAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) MembersSetRole(
	ctx context.Context,
	request *nordlet.MembersSetRoleAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.MembersSetRoleAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/members/set-role"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.MembersSetRoleAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.MembersSetRoleAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) MembersTransferOwnership(
	ctx context.Context,
	request *nordlet.MembersTransferOwnershipAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.MembersTransferOwnershipAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/members/transfer-ownership"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.MembersTransferOwnershipAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.MembersTransferOwnershipAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) MembersRemove(
	ctx context.Context,
	request *nordlet.MembersRemoveAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.MembersRemoveAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/members/remove"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.MembersRemoveAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.MembersRemoveAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) InvitesCreate(
	ctx context.Context,
	request *nordlet.InvitesCreateAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.InvitesCreateAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/invites/create"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.InvitesCreateAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.InvitesCreateAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) InvitesList(
	ctx context.Context,
	request *nordlet.InvitesListAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.InvitesListAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/invites/list"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.InvitesListAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.InvitesListAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) InvitesRevoke(
	ctx context.Context,
	request *nordlet.InvitesRevokeAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.InvitesRevokeAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/invites/revoke"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.InvitesRevokeAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.InvitesRevokeAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) InvitesGet(
	ctx context.Context,
	request *nordlet.InvitesGetAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.InvitesGetAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/invites/get"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.InvitesGetAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.InvitesGetAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) InvitesAccept(
	ctx context.Context,
	request *nordlet.InvitesAcceptAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.InvitesAcceptAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/invites/accept"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.InvitesAcceptAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.InvitesAcceptAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) LocaleSet(
	ctx context.Context,
	request *nordlet.LocaleSetAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.LocaleSetAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/locale/set"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.LocaleSetAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.LocaleSetAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CompaniesCreate(
	ctx context.Context,
	request *nordlet.CompaniesCreateAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.CompaniesCreateAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/companies/create"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.CompaniesCreateAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.CompaniesCreateAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CompaniesSelect(
	ctx context.Context,
	request *nordlet.CompaniesSelectAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.CompaniesSelectAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/companies/select"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.CompaniesSelectAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.CompaniesSelectAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CompaniesProfile(
	ctx context.Context,
	request *nordlet.CompaniesProfileAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.CompaniesProfileAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/companies/profile"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.CompaniesProfileAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.CompaniesProfileAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CompaniesUpdate(
	ctx context.Context,
	request *nordlet.CompaniesUpdateAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.CompaniesUpdateAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/companies/update"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.CompaniesUpdateAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.CompaniesUpdateAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CompaniesArchive(
	ctx context.Context,
	request *nordlet.CompaniesArchiveAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.CompaniesArchiveAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/companies/archive"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.CompaniesArchiveAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.CompaniesArchiveAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CompaniesDelete(
	ctx context.Context,
	request *nordlet.CompaniesDeleteAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.CompaniesDeleteAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/companies/delete"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.CompaniesDeleteAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.CompaniesDeleteAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CompaniesActivate(
	ctx context.Context,
	request *nordlet.CompaniesActivateAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.CompaniesActivateAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/companies/activate"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.CompaniesActivateAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.CompaniesActivateAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) APIKeysCreate(
	ctx context.Context,
	request *nordlet.APIKeysCreateAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.APIKeysCreateAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/api-keys/create"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.APIKeysCreateAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.APIKeysCreateAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) APIKeysList(
	ctx context.Context,
	request *nordlet.APIKeysListAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.APIKeysListAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/api-keys/list"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.APIKeysListAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.APIKeysListAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) APIKeysRotate(
	ctx context.Context,
	request *nordlet.APIKeysRotateAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.APIKeysRotateAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/api-keys/rotate"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.APIKeysRotateAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.APIKeysRotateAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) APIKeysRevoke(
	ctx context.Context,
	request *nordlet.APIKeysRevokeAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.APIKeysRevokeAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/api-keys/revoke"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.APIKeysRevokeAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.APIKeysRevokeAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ConsentAccept(
	ctx context.Context,
	request *nordlet.ConsentAcceptAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.ConsentAcceptAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/consent/accept"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.ConsentAcceptAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.ConsentAcceptAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ProfileUpdate(
	ctx context.Context,
	request *nordlet.ProfileUpdateAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.ProfileUpdateAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/profile/update"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.ProfileUpdateAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.ProfileUpdateAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) EmailChangeRequest(
	ctx context.Context,
	request *nordlet.EmailChangeRequestAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.EmailChangeRequestAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/email/change-request"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.EmailChangeRequestAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.EmailChangeRequestAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) SessionsList(
	ctx context.Context,
	request *nordlet.SessionsListAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.SessionsListAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/sessions/list"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.SessionsListAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.SessionsListAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) SessionsRevoke(
	ctx context.Context,
	request *nordlet.SessionsRevokeAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.SessionsRevokeAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/sessions/revoke"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.SessionsRevokeAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.SessionsRevokeAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) SessionsRevokeOthers(
	ctx context.Context,
	request *nordlet.SessionsRevokeOthersAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.SessionsRevokeOthersAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/sessions/revoke-others"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.SessionsRevokeOthersAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.SessionsRevokeOthersAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Export(
	ctx context.Context,
	request *nordlet.ExportAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.ExportAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/export"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.ExportAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.ExportAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Delete(
	ctx context.Context,
	request *nordlet.DeleteAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.DeleteAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/delete"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.DeleteAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.DeleteAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ReferralGet(
	ctx context.Context,
	request *nordlet.ReferralGetAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.ReferralGetAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/referral/get"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.ReferralGetAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.ReferralGetAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ReferralConvert(
	ctx context.Context,
	request *nordlet.ReferralConvertAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.ReferralConvertAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/referral/convert"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.ReferralConvertAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.ReferralConvertAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) TableSettingsGet(
	ctx context.Context,
	request *nordlet.TableSettingsGetAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.TableSettingsGetAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/table-settings/get"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.TableSettingsGetAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.TableSettingsGetAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) TableSettingsSet(
	ctx context.Context,
	request *nordlet.TableSettingsSetAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.TableSettingsSetAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/table-settings/set"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.TableSettingsSetAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.TableSettingsSetAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) TableSettingsList(
	ctx context.Context,
	request *nordlet.TableSettingsListAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.TableSettingsListAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/account/table-settings/list"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.TableSettingsListAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.TableSettingsListAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
