// Code generated by Fern. DO NOT EDIT.

package transport

import (
	context "context"

	nordlet "github.com/nordlet/nordlet-sdk-go"
	core "github.com/nordlet/nordlet-sdk-go/core"
	internal "github.com/nordlet/nordlet-sdk-go/internal"
	option "github.com/nordlet/nordlet-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (c *Client) PostV1TransportWaybillsCreate(
	ctx context.Context,
	request *nordlet.PostV1TransportWaybillsCreateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1TransportWaybillsCreateResponse, error) {
	response, err := c.WithRawResponse.PostV1TransportWaybillsCreate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1TransportWaybillsUpdate(
	ctx context.Context,
	request *nordlet.PostV1TransportWaybillsUpdateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1TransportWaybillsUpdateResponse, error) {
	response, err := c.WithRawResponse.PostV1TransportWaybillsUpdate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1TransportWaybillsIssue(
	ctx context.Context,
	request *nordlet.PostV1TransportWaybillsIssueRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1TransportWaybillsIssueResponse, error) {
	response, err := c.WithRawResponse.PostV1TransportWaybillsIssue(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1TransportWaybillsCancel(
	ctx context.Context,
	request *nordlet.PostV1TransportWaybillsCancelRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1TransportWaybillsCancelResponse, error) {
	response, err := c.WithRawResponse.PostV1TransportWaybillsCancel(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1TransportWaybillsGet(
	ctx context.Context,
	request *nordlet.PostV1TransportWaybillsGetRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1TransportWaybillsGetResponse, error) {
	response, err := c.WithRawResponse.PostV1TransportWaybillsGet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1TransportWaybillsList(
	ctx context.Context,
	request *nordlet.PostV1TransportWaybillsListRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1TransportWaybillsListResponse, error) {
	response, err := c.WithRawResponse.PostV1TransportWaybillsList(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
