// Code generated by Fern. DO NOT EDIT.

package transport

import (
	context "context"

	nordlet "github.com/nordlet/nordlet-sdk-go"
	core "github.com/nordlet/nordlet-sdk-go/core"
	internal "github.com/nordlet/nordlet-sdk-go/internal"
	option "github.com/nordlet/nordlet-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (c *Client) WaybillsCreate(
	ctx context.Context,
	request *nordlet.WaybillsCreateTransportRequest,
	opts ...option.RequestOption,
) (*nordlet.WaybillsCreateTransportResponse, error) {
	response, err := c.WithRawResponse.WaybillsCreate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) WaybillsUpdate(
	ctx context.Context,
	request *nordlet.WaybillsUpdateTransportRequest,
	opts ...option.RequestOption,
) (*nordlet.WaybillsUpdateTransportResponse, error) {
	response, err := c.WithRawResponse.WaybillsUpdate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) WaybillsIssue(
	ctx context.Context,
	request *nordlet.WaybillsIssueTransportRequest,
	opts ...option.RequestOption,
) (*nordlet.WaybillsIssueTransportResponse, error) {
	response, err := c.WithRawResponse.WaybillsIssue(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) WaybillsCancel(
	ctx context.Context,
	request *nordlet.WaybillsCancelTransportRequest,
	opts ...option.RequestOption,
) (*nordlet.WaybillsCancelTransportResponse, error) {
	response, err := c.WithRawResponse.WaybillsCancel(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) WaybillsGet(
	ctx context.Context,
	request *nordlet.WaybillsGetTransportRequest,
	opts ...option.RequestOption,
) (*nordlet.WaybillsGetTransportResponse, error) {
	response, err := c.WithRawResponse.WaybillsGet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) WaybillsList(
	ctx context.Context,
	request *nordlet.WaybillsListTransportRequest,
	opts ...option.RequestOption,
) (*nordlet.WaybillsListTransportResponse, error) {
	response, err := c.WithRawResponse.WaybillsList(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
