// Code generated by Fern. DO NOT EDIT.

package hr

import (
	context "context"

	nordlet "github.com/nordlet/nordlet-sdk-go"
	core "github.com/nordlet/nordlet-sdk-go/core"
	internal "github.com/nordlet/nordlet-sdk-go/internal"
	option "github.com/nordlet/nordlet-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (c *Client) PostV1HrPositionsCreate(
	ctx context.Context,
	request *nordlet.PostV1HrPositionsCreateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1HrPositionsCreateResponse, error) {
	response, err := c.WithRawResponse.PostV1HrPositionsCreate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1HrPositionsUpdate(
	ctx context.Context,
	request *nordlet.PostV1HrPositionsUpdateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1HrPositionsUpdateResponse, error) {
	response, err := c.WithRawResponse.PostV1HrPositionsUpdate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1HrPositionsList(
	ctx context.Context,
	request *nordlet.PostV1HrPositionsListRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1HrPositionsListResponse, error) {
	response, err := c.WithRawResponse.PostV1HrPositionsList(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1HrEmployeesCreate(
	ctx context.Context,
	request *nordlet.PostV1HrEmployeesCreateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1HrEmployeesCreateResponse, error) {
	response, err := c.WithRawResponse.PostV1HrEmployeesCreate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1HrEmployeesUpdate(
	ctx context.Context,
	request *nordlet.PostV1HrEmployeesUpdateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1HrEmployeesUpdateResponse, error) {
	response, err := c.WithRawResponse.PostV1HrEmployeesUpdate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1HrEmployeesGet(
	ctx context.Context,
	request *nordlet.PostV1HrEmployeesGetRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1HrEmployeesGetResponse, error) {
	response, err := c.WithRawResponse.PostV1HrEmployeesGet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1HrEmployeesList(
	ctx context.Context,
	request *nordlet.PostV1HrEmployeesListRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1HrEmployeesListResponse, error) {
	response, err := c.WithRawResponse.PostV1HrEmployeesList(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1HrContractsCreate(
	ctx context.Context,
	request *nordlet.PostV1HrContractsCreateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1HrContractsCreateResponse, error) {
	response, err := c.WithRawResponse.PostV1HrContractsCreate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1HrContractsEnd(
	ctx context.Context,
	request *nordlet.PostV1HrContractsEndRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1HrContractsEndResponse, error) {
	response, err := c.WithRawResponse.PostV1HrContractsEnd(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1HrContractsList(
	ctx context.Context,
	request *nordlet.PostV1HrContractsListRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1HrContractsListResponse, error) {
	response, err := c.WithRawResponse.PostV1HrContractsList(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1HrLeaveBalancesSet(
	ctx context.Context,
	request *nordlet.PostV1HrLeaveBalancesSetRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1HrLeaveBalancesSetResponse, error) {
	response, err := c.WithRawResponse.PostV1HrLeaveBalancesSet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1HrLeaveBalancesList(
	ctx context.Context,
	request *nordlet.PostV1HrLeaveBalancesListRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1HrLeaveBalancesListResponse, error) {
	response, err := c.WithRawResponse.PostV1HrLeaveBalancesList(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1HrIncapacityCertificatesCreate(
	ctx context.Context,
	request *nordlet.PostV1HrIncapacityCertificatesCreateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1HrIncapacityCertificatesCreateResponse, error) {
	response, err := c.WithRawResponse.PostV1HrIncapacityCertificatesCreate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1HrIncapacityCertificatesList(
	ctx context.Context,
	request *nordlet.PostV1HrIncapacityCertificatesListRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1HrIncapacityCertificatesListResponse, error) {
	response, err := c.WithRawResponse.PostV1HrIncapacityCertificatesList(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1HrEmployeesRecordsCreate(
	ctx context.Context,
	request *nordlet.PostV1HrEmployeesRecordsCreateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1HrEmployeesRecordsCreateResponse, error) {
	response, err := c.WithRawResponse.PostV1HrEmployeesRecordsCreate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1HrEmployeesRecordsUpdate(
	ctx context.Context,
	request *nordlet.PostV1HrEmployeesRecordsUpdateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1HrEmployeesRecordsUpdateResponse, error) {
	response, err := c.WithRawResponse.PostV1HrEmployeesRecordsUpdate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1HrEmployeesRecordsDelete(
	ctx context.Context,
	request *nordlet.PostV1HrEmployeesRecordsDeleteRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1HrEmployeesRecordsDeleteResponse, error) {
	response, err := c.WithRawResponse.PostV1HrEmployeesRecordsDelete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1HrEmployeesRecordsList(
	ctx context.Context,
	request *nordlet.PostV1HrEmployeesRecordsListRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1HrEmployeesRecordsListResponse, error) {
	response, err := c.WithRawResponse.PostV1HrEmployeesRecordsList(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1HrEmployeesAttachmentsList(
	ctx context.Context,
	request *nordlet.PostV1HrEmployeesAttachmentsListRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1HrEmployeesAttachmentsListResponse, error) {
	response, err := c.WithRawResponse.PostV1HrEmployeesAttachmentsList(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1HrTimesheetsGenerate(
	ctx context.Context,
	request *nordlet.PostV1HrTimesheetsGenerateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1HrTimesheetsGenerateResponse, error) {
	response, err := c.WithRawResponse.PostV1HrTimesheetsGenerate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1HrTimesheetsUpsert(
	ctx context.Context,
	request *nordlet.PostV1HrTimesheetsUpsertRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1HrTimesheetsUpsertResponse, error) {
	response, err := c.WithRawResponse.PostV1HrTimesheetsUpsert(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1HrTimesheetsGet(
	ctx context.Context,
	request *nordlet.PostV1HrTimesheetsGetRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1HrTimesheetsGetResponse, error) {
	response, err := c.WithRawResponse.PostV1HrTimesheetsGet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1HrTimesheetsList(
	ctx context.Context,
	request *nordlet.PostV1HrTimesheetsListRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1HrTimesheetsListResponse, error) {
	response, err := c.WithRawResponse.PostV1HrTimesheetsList(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1HrTimesheetsDelete(
	ctx context.Context,
	request *nordlet.PostV1HrTimesheetsDeleteRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1HrTimesheetsDeleteResponse, error) {
	response, err := c.WithRawResponse.PostV1HrTimesheetsDelete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
