// Code generated by Fern. DO NOT EDIT.

package ledger

import (
	context "context"
	http "net/http"

	nordlet "github.com/nordlet/nordlet-sdk-go"
	core "github.com/nordlet/nordlet-sdk-go/core"
	internal "github.com/nordlet/nordlet-sdk-go/internal"
	option "github.com/nordlet/nordlet-sdk-go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) PostV1LedgerAccountsList(
	ctx context.Context,
	request *nordlet.PostV1LedgerAccountsListRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1LedgerAccountsListResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/ledger/accounts/list"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1LedgerAccountsListResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1LedgerAccountsListResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1LedgerAccountsCreate(
	ctx context.Context,
	request *nordlet.PostV1LedgerAccountsCreateRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1LedgerAccountsCreateResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/ledger/accounts/create"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1LedgerAccountsCreateResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1LedgerAccountsCreateResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1LedgerAccountsUpdate(
	ctx context.Context,
	request *nordlet.PostV1LedgerAccountsUpdateRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1LedgerAccountsUpdateResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/ledger/accounts/update"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1LedgerAccountsUpdateResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1LedgerAccountsUpdateResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1LedgerAccountsApplyTemplate(
	ctx context.Context,
	request *nordlet.PostV1LedgerAccountsApplyTemplateRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1LedgerAccountsApplyTemplateResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/ledger/accounts/apply-template"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1LedgerAccountsApplyTemplateResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1LedgerAccountsApplyTemplateResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1LedgerPeriodsList(
	ctx context.Context,
	request *nordlet.PostV1LedgerPeriodsListRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1LedgerPeriodsListResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/ledger/periods/list"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1LedgerPeriodsListResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1LedgerPeriodsListResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1LedgerPeriodsLock(
	ctx context.Context,
	request *nordlet.PostV1LedgerPeriodsLockRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1LedgerPeriodsLockResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/ledger/periods/lock"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1LedgerPeriodsLockResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1LedgerPeriodsLockResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1LedgerPeriodsUnlock(
	ctx context.Context,
	request *nordlet.PostV1LedgerPeriodsUnlockRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1LedgerPeriodsUnlockResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/ledger/periods/unlock"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1LedgerPeriodsUnlockResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1LedgerPeriodsUnlockResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1LedgerJournalTransactionsList(
	ctx context.Context,
	request *nordlet.PostV1LedgerJournalTransactionsListRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1LedgerJournalTransactionsListResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/ledger/journal/transactions/list"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1LedgerJournalTransactionsListResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1LedgerJournalTransactionsListResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1LedgerCostCentersCreate(
	ctx context.Context,
	request *nordlet.PostV1LedgerCostCentersCreateRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1LedgerCostCentersCreateResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/ledger/cost-centers/create"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1LedgerCostCentersCreateResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1LedgerCostCentersCreateResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1LedgerCostCentersUpdate(
	ctx context.Context,
	request *nordlet.PostV1LedgerCostCentersUpdateRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1LedgerCostCentersUpdateResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/ledger/cost-centers/update"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1LedgerCostCentersUpdateResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1LedgerCostCentersUpdateResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1LedgerCostCentersList(
	ctx context.Context,
	request *nordlet.PostV1LedgerCostCentersListRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1LedgerCostCentersListResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/ledger/cost-centers/list"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1LedgerCostCentersListResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1LedgerCostCentersListResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1LedgerCostCenterGroupsCreate(
	ctx context.Context,
	request *nordlet.PostV1LedgerCostCenterGroupsCreateRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1LedgerCostCenterGroupsCreateResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/ledger/cost-center-groups/create"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1LedgerCostCenterGroupsCreateResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1LedgerCostCenterGroupsCreateResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1LedgerCostCenterGroupsUpdate(
	ctx context.Context,
	request *nordlet.PostV1LedgerCostCenterGroupsUpdateRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1LedgerCostCenterGroupsUpdateResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/ledger/cost-center-groups/update"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1LedgerCostCenterGroupsUpdateResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1LedgerCostCenterGroupsUpdateResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1LedgerCostCenterGroupsDelete(
	ctx context.Context,
	request *nordlet.PostV1LedgerCostCenterGroupsDeleteRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1LedgerCostCenterGroupsDeleteResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/ledger/cost-center-groups/delete"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1LedgerCostCenterGroupsDeleteResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1LedgerCostCenterGroupsDeleteResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1LedgerCostCenterGroupsList(
	ctx context.Context,
	request *nordlet.PostV1LedgerCostCenterGroupsListRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1LedgerCostCenterGroupsListResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/ledger/cost-center-groups/list"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1LedgerCostCenterGroupsListResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1LedgerCostCenterGroupsListResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1LedgerPostingRulesList(
	ctx context.Context,
	request *nordlet.PostV1LedgerPostingRulesListRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1LedgerPostingRulesListResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/ledger/posting-rules/list"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1LedgerPostingRulesListResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1LedgerPostingRulesListResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1LedgerPostingRulesUpdate(
	ctx context.Context,
	request *nordlet.PostV1LedgerPostingRulesUpdateRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1LedgerPostingRulesUpdateResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/ledger/posting-rules/update"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1LedgerPostingRulesUpdateResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1LedgerPostingRulesUpdateResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1LedgerOwnersCreate(
	ctx context.Context,
	request *nordlet.PostV1LedgerOwnersCreateRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1LedgerOwnersCreateResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/ledger/owners/create"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1LedgerOwnersCreateResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1LedgerOwnersCreateResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1LedgerOwnersUpdate(
	ctx context.Context,
	request *nordlet.PostV1LedgerOwnersUpdateRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1LedgerOwnersUpdateResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/ledger/owners/update"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1LedgerOwnersUpdateResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1LedgerOwnersUpdateResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1LedgerOwnersDelete(
	ctx context.Context,
	request *nordlet.PostV1LedgerOwnersDeleteRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1LedgerOwnersDeleteResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/ledger/owners/delete"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1LedgerOwnersDeleteResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1LedgerOwnersDeleteResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1LedgerOwnersList(
	ctx context.Context,
	request *nordlet.PostV1LedgerOwnersListRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1LedgerOwnersListResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/ledger/owners/list"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1LedgerOwnersListResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1LedgerOwnersListResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1LedgerJournalTransactionsGet(
	ctx context.Context,
	request *nordlet.PostV1LedgerJournalTransactionsGetRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1LedgerJournalTransactionsGetResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/ledger/journal/transactions/get"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1LedgerJournalTransactionsGetResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1LedgerJournalTransactionsGetResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1LedgerJournalTransactionsCreate(
	ctx context.Context,
	request *nordlet.PostV1LedgerJournalTransactionsCreateRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1LedgerJournalTransactionsCreateResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/ledger/journal/transactions/create"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1LedgerJournalTransactionsCreateResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1LedgerJournalTransactionsCreateResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
