// Code generated by Fern. DO NOT EDIT.

package declarations

import (
	context "context"

	nordlet "github.com/nordlet/nordlet-sdk-go"
	core "github.com/nordlet/nordlet-sdk-go/core"
	internal "github.com/nordlet/nordlet-sdk-go/internal"
	option "github.com/nordlet/nordlet-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (c *Client) PostV1DeclarationsLtIntrastatCompute(
	ctx context.Context,
	request *nordlet.PostV1DeclarationsLtIntrastatComputeRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1DeclarationsLtIntrastatComputeResponse, error) {
	response, err := c.WithRawResponse.PostV1DeclarationsLtIntrastatCompute(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1DeclarationsLtIvazGenerate(
	ctx context.Context,
	request *nordlet.PostV1DeclarationsLtIvazGenerateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1DeclarationsLtIvazGenerateResponse, error) {
	response, err := c.WithRawResponse.PostV1DeclarationsLtIvazGenerate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1DeclarationsLtIntrastatObligation(
	ctx context.Context,
	request *nordlet.PostV1DeclarationsLtIntrastatObligationRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1DeclarationsLtIntrastatObligationResponse, error) {
	response, err := c.WithRawResponse.PostV1DeclarationsLtIntrastatObligation(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1DeclarationsLtIsafGenerate(
	ctx context.Context,
	request *nordlet.PostV1DeclarationsLtIsafGenerateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1DeclarationsLtIsafGenerateResponse, error) {
	response, err := c.WithRawResponse.PostV1DeclarationsLtIsafGenerate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1DeclarationsLtFr0600Compute(
	ctx context.Context,
	request *nordlet.PostV1DeclarationsLtFr0600ComputeRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1DeclarationsLtFr0600ComputeResponse, error) {
	response, err := c.WithRawResponse.PostV1DeclarationsLtFr0600Compute(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1DeclarationsLtGpm313Compute(
	ctx context.Context,
	request *nordlet.PostV1DeclarationsLtGpm313ComputeRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1DeclarationsLtGpm313ComputeResponse, error) {
	response, err := c.WithRawResponse.PostV1DeclarationsLtGpm313Compute(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1DeclarationsLtSamCompute(
	ctx context.Context,
	request *nordlet.PostV1DeclarationsLtSamComputeRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1DeclarationsLtSamComputeResponse, error) {
	response, err := c.WithRawResponse.PostV1DeclarationsLtSamCompute(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1DeclarationsLtSdGenerate(
	ctx context.Context,
	request *nordlet.PostV1DeclarationsLtSdGenerateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1DeclarationsLtSdGenerateResponse, error) {
	response, err := c.WithRawResponse.PostV1DeclarationsLtSdGenerate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1DeclarationsLtSaftGenerate(
	ctx context.Context,
	request *nordlet.PostV1DeclarationsLtSaftGenerateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1DeclarationsLtSaftGenerateResponse, error) {
	response, err := c.WithRawResponse.PostV1DeclarationsLtSaftGenerate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1DeclarationsEuOssCompute(
	ctx context.Context,
	request *nordlet.PostV1DeclarationsEuOssComputeRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1DeclarationsEuOssComputeResponse, error) {
	response, err := c.WithRawResponse.PostV1DeclarationsEuOssCompute(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1DeclarationsEuIossCompute(
	ctx context.Context,
	request *nordlet.PostV1DeclarationsEuIossComputeRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1DeclarationsEuIossComputeResponse, error) {
	response, err := c.WithRawResponse.PostV1DeclarationsEuIossCompute(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1DeclarationsEuDistanceSalesThresholdGet(
	ctx context.Context,
	request *nordlet.PostV1DeclarationsEuDistanceSalesThresholdGetRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1DeclarationsEuDistanceSalesThresholdGetResponse, error) {
	response, err := c.WithRawResponse.PostV1DeclarationsEuDistanceSalesThresholdGet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1DeclarationsEuUnionTurnoverGet(
	ctx context.Context,
	request *nordlet.PostV1DeclarationsEuUnionTurnoverGetRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1DeclarationsEuUnionTurnoverGetResponse, error) {
	response, err := c.WithRawResponse.PostV1DeclarationsEuUnionTurnoverGet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1DeclarationsEuSmeCrossBorderReportCompute(
	ctx context.Context,
	request *nordlet.PostV1DeclarationsEuSmeCrossBorderReportComputeRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1DeclarationsEuSmeCrossBorderReportComputeResponse, error) {
	response, err := c.WithRawResponse.PostV1DeclarationsEuSmeCrossBorderReportCompute(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1DeclarationsEuSmeThresholdsList(
	ctx context.Context,
	request *nordlet.PostV1DeclarationsEuSmeThresholdsListRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1DeclarationsEuSmeThresholdsListResponse, error) {
	response, err := c.WithRawResponse.PostV1DeclarationsEuSmeThresholdsList(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1DeclarationsEuSmeThresholdGet(
	ctx context.Context,
	request *nordlet.PostV1DeclarationsEuSmeThresholdGetRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1DeclarationsEuSmeThresholdGetResponse, error) {
	response, err := c.WithRawResponse.PostV1DeclarationsEuSmeThresholdGet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1DeclarationsEuVatReturnPacksList(
	ctx context.Context,
	request *nordlet.PostV1DeclarationsEuVatReturnPacksListRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1DeclarationsEuVatReturnPacksListResponse, error) {
	response, err := c.WithRawResponse.PostV1DeclarationsEuVatReturnPacksList(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1DeclarationsEuVatReturnCompute(
	ctx context.Context,
	request *nordlet.PostV1DeclarationsEuVatReturnComputeRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1DeclarationsEuVatReturnComputeResponse, error) {
	response, err := c.WithRawResponse.PostV1DeclarationsEuVatReturnCompute(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1DeclarationsConfigsList(
	ctx context.Context,
	request *nordlet.PostV1DeclarationsConfigsListRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1DeclarationsConfigsListResponse, error) {
	response, err := c.WithRawResponse.PostV1DeclarationsConfigsList(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1DeclarationsConfigsUpdate(
	ctx context.Context,
	request *nordlet.PostV1DeclarationsConfigsUpdateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1DeclarationsConfigsUpdateResponse, error) {
	response, err := c.WithRawResponse.PostV1DeclarationsConfigsUpdate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1DeclarationsSubmissionsCreate(
	ctx context.Context,
	request *nordlet.PostV1DeclarationsSubmissionsCreateRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1DeclarationsSubmissionsCreateResponse, error) {
	response, err := c.WithRawResponse.PostV1DeclarationsSubmissionsCreate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1DeclarationsSubmissionsMark(
	ctx context.Context,
	request *nordlet.PostV1DeclarationsSubmissionsMarkRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1DeclarationsSubmissionsMarkResponse, error) {
	response, err := c.WithRawResponse.PostV1DeclarationsSubmissionsMark(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) PostV1DeclarationsSubmissionsList(
	ctx context.Context,
	request *nordlet.PostV1DeclarationsSubmissionsListRequest,
	opts ...option.RequestOption,
) (*nordlet.PostV1DeclarationsSubmissionsListResponse, error) {
	response, err := c.WithRawResponse.PostV1DeclarationsSubmissionsList(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
