// Code generated by Fern. DO NOT EDIT.

package files

import (
	context "context"
	http "net/http"

	nordlet "github.com/nordlet/nordlet-sdk-go"
	core "github.com/nordlet/nordlet-sdk-go/core"
	internal "github.com/nordlet/nordlet-sdk-go/internal"
	option "github.com/nordlet/nordlet-sdk-go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) PostV1FilesUpload(
	ctx context.Context,
	request *nordlet.PostV1FilesUploadRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1FilesUploadResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/files/upload"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1FilesUploadResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1FilesUploadResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1FilesGet(
	ctx context.Context,
	request *nordlet.PostV1FilesGetRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1FilesGetResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/files/get"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1FilesGetResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1FilesGetResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1FilesList(
	ctx context.Context,
	request *nordlet.PostV1FilesListRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1FilesListResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/files/list"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1FilesListResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1FilesListResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PostV1FilesDelete(
	ctx context.Context,
	request *nordlet.PostV1FilesDeleteRequest,
	opts ...option.RequestOption,
) (*core.Response[*nordlet.PostV1FilesDeleteResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.nordlet.com",
	)
	endpointURL := baseURL + "/v1/files/delete"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *nordlet.PostV1FilesDeleteResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(nordlet.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*nordlet.PostV1FilesDeleteResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
